import React,{useState} from 'react';
import {Head,router} from '@inertiajs/react';
import {CheckCircle2,ExternalLink,Image,ShieldCheck,WalletCards,XCircle} from 'lucide-react';
import Layout from '../../components/Layout';
import {EmptyState, PageHeader} from '../../components/Ui';
import {useAccess} from '../../hooks/useAccess';

const rp=(v:any)=>'Rp '+Number(v||0).toLocaleString('id-ID');

export default function ManualPayments({proofs,filters}:any){
  const {can}=useAccess();
  const canManage=can('billing.manage');
  const [status,setStatus]=useState(filters?.status||'pending');
  return <Layout><Head title="Bukti Pembayaran"/><div className="space-y-6">
    <PageHeader eyebrow="Payment Verification" title="Verifikasi Bukti Pembayaran" description="Review transfer manual dari Customer Portal. Invoice baru berubah setelah bukti disetujui." actions={<select value={status} onChange={e=>{setStatus(e.target.value);router.get('/billing/manual-payments',{status:e.target.value},{preserveState:true,replace:true})}} className="rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm font-semibold text-slate-700"><option value="pending">Menunggu Review</option><option value="approved">Disetujui</option><option value="rejected">Ditolak</option><option value="">Semua Status</option></select>}/>
    {!canManage&&<div className="flex items-center gap-3 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800"><ShieldCheck size={20} className="shrink-0"/><div><b>Mode read-only.</b> Anda dapat melihat bukti pembayaran, tetapi approval/rejection membutuhkan permission <code>billing.manage</code>.</div></div>}
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-[1080px] w-full text-sm"><thead className="bg-slate-50 text-left text-[11px] font-extrabold uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Pelanggan</th><th className="px-4 py-3">Invoice</th><th className="px-4 py-3">Metode</th><th className="px-4 py-3">Nominal</th><th className="px-4 py-3">Bukti</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Aksi</th></tr></thead><tbody>{proofs.data.map((p:any)=><ProofRow key={p.id} proof={p} canManage={canManage}/>)}</tbody></table></div>{!proofs.data.length&&<EmptyState text="Tidak ada bukti pembayaran pada filter ini."/>}<div className="flex items-center justify-between border-t border-slate-100 p-4 text-sm"><button disabled={!proofs.prev_page_url} className="jk-btn secondary disabled:opacity-30" onClick={()=>proofs.prev_page_url&&router.visit(proofs.prev_page_url)}>← Sebelumnya</button><span className="text-xs font-semibold text-slate-500">Halaman {proofs.current_page}/{proofs.last_page}</span><button disabled={!proofs.next_page_url} className="jk-btn secondary disabled:opacity-30" onClick={()=>proofs.next_page_url&&router.visit(proofs.next_page_url)}>Berikutnya →</button></div></section>
  </div></Layout>;
}

function ProofRow({proof,canManage}:{proof:any;canManage:boolean}){
  const [note,setNote]=useState('');
  const review=(action:'approve'|'reject')=>{if(!canManage)return;if(action==='approve'&&!confirm(`Setujui pembayaran ${rp(proof.amount)} untuk ${proof.invoice?.invoice_number}?`))return;if(action==='reject'&&!confirm('Tolak bukti pembayaran ini?'))return;router.put(`/billing/manual-payments/${proof.id}`,{action,review_note:note},{preserveScroll:true})};
  return <tr className="border-t border-slate-100 align-top transition hover:bg-slate-50/70"><td className="px-4 py-4"><div className="font-extrabold text-slate-800">{proof.customer?.name}</div><div className="mt-1 text-xs text-slate-500">{proof.customer?.customer_number} · {proof.customer?.phone||'-'}</div></td><td className="px-4 py-4"><div className="font-bold text-slate-800">{proof.invoice?.invoice_number}</div><div className="mt-1 text-xs text-slate-500">Sisa {rp(proof.invoice?.balance_due)}</div></td><td className="px-4 py-4"><div className="font-semibold text-slate-700">{proof.method?.name}</div><div className="mt-1 text-xs text-slate-500">{proof.method?.account_name} {proof.method?.account_number}</div></td><td className="px-4 py-4 font-black text-slate-900">{rp(proof.amount)}<div className="mt-1 text-xs font-normal text-slate-500">{proof.payer_name||'-'} · {proof.reference||'tanpa referensi'}</div></td><td className="px-4 py-4"><a href={`/billing/manual-payments/${proof.id}/file`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs font-bold text-[var(--jk-primary)] hover:bg-slate-50"><Image size={14}/> Lihat Bukti <ExternalLink size={12}/></a></td><td className="px-4 py-4"><Status value={proof.status}/>{proof.payment?.payment_number&&<div className="mt-2 flex items-center gap-1 text-xs font-bold text-emerald-700"><WalletCards size={13}/>{proof.payment.payment_number}</div>}</td><td className="px-4 py-4">{proof.status==='pending'&&canManage?<div className="w-64"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Catatan review (opsional)" className="w-full rounded-lg border border-slate-300 px-2.5 py-2 text-xs outline-none focus:border-[var(--jk-primary)]"/><div className="mt-2 flex gap-2"><button onClick={()=>review('approve')} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-2.5 py-2 text-xs font-bold text-white hover:bg-emerald-700"><CheckCircle2 size={14}/> Setujui</button><button onClick={()=>review('reject')} className="inline-flex items-center gap-1 rounded-lg bg-rose-50 px-2.5 py-2 text-xs font-bold text-rose-700 hover:bg-rose-100"><XCircle size={14}/> Tolak</button></div></div>:<div className="text-xs leading-5 text-slate-500">{proof.status==='pending'&&!canManage?'Menunggu reviewer berizin.':proof.review_note||'Sudah direview'}{proof.reviewer?.name&&<div className="font-semibold text-slate-600">{proof.reviewer.name}</div>}</div>}</td></tr>;
}

function Status({value}:{value:string}){const cls=value==='approved'?'bg-emerald-50 text-emerald-700 ring-emerald-200':value==='rejected'?'bg-rose-50 text-rose-700 ring-rose-200':'bg-amber-50 text-amber-700 ring-amber-200';return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-black uppercase ring-1 ${cls}`}>{value}</span>}
