import React from 'react';
import {Head, Link, router, useForm} from '@inertiajs/react';
import {CalendarDays, CircleDollarSign, CreditCard, Download, History, Landmark, ReceiptText, ShieldCheck, UserRound, Wifi} from 'lucide-react';
import Layout from '../../components/Layout';
import {EmptyState, MetricCard, PageHeader, Surface} from '../../components/Ui';
import {useAccess} from '../../hooks/useAccess';

const input='w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none transition focus:border-[var(--jk-primary)] focus:ring-2 focus:ring-blue-100';
const idempotencyKey=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}`;

export default function BillingShow({invoice,paymentMethods,gateway}:{invoice:any,paymentMethods:string[],gateway:any}){
  const {can}=useAccess();
  const canManage=can('billing.manage');
  const form=useForm({amount:invoice.balance_due||0,method:'cash',reference:'',paid_at:new Date().toISOString().slice(0,16),notes:'',idempotency_key:idempotencyKey()});
  const canPay=canManage&&invoice.balance_due>0&&!['void','paid'].includes(invoice.status);

  return <Layout>
    <Head title={invoice.invoice_number}/>
    <div className="mx-auto max-w-7xl space-y-6">
      <PageHeader eyebrow="Invoice Detail" title={invoice.invoice_number} description={`${invoice.customer?.customer_number||'-'} · ${invoice.customer?.name||'Pelanggan'}`} actions={<><Link href="/billing" className="jk-btn secondary">← Billing</Link><a href={`/billing/invoices/${invoice.id}/download`} className="jk-btn secondary"><Download size={15}/>Unduh PDF</a><Status value={invoice.status}/></>}/>

      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <MetricCard icon={ReceiptText} label="Total Invoice" value={rupiah(invoice.total)} hint={`${date(invoice.period_start)} — ${date(invoice.period_end)}`} tone="blue"/>
        <MetricCard icon={CircleDollarSign} label="Terbayar" value={rupiah(invoice.paid_amount)} hint={invoice.paid_at?`Lunas ${dateTime(invoice.paid_at)}`:'Pembayaran teralokasi'} tone="emerald"/>
        <MetricCard icon={CreditCard} label="Sisa Tagihan" value={rupiah(invoice.balance_due)} hint={invoice.balance_due>0?`Jatuh tempo ${date(invoice.due_at)}`:'Tidak ada saldo'} tone={invoice.status==='overdue'?'rose':'amber'}/>
        <MetricCard icon={CalendarDays} label="Jatuh Tempo" value={date(invoice.due_at)} hint={`Terbit ${date(invoice.issued_at)}`} tone="violet"/>
      </section>

      <section className="grid gap-4 lg:grid-cols-3">
        <Surface title="Pelanggan"><div className="space-y-3 text-sm"><InfoRow icon={UserRound} label="Customer" value={`${invoice.customer?.customer_number||'-'} · ${invoice.customer?.name||'-'}`}/><InfoRow label="Phone" value={invoice.customer?.phone||'-'}/><InfoRow label="Email" value={invoice.customer?.email||'-'}/><Link href={`/customers/${invoice.customer?.id}`} className="inline-flex text-xs font-extrabold text-[var(--jk-primary)] hover:underline">Buka Customer 360 →</Link></div></Surface>
        <Surface title="Layanan"><div className="space-y-3 text-sm"><InfoRow icon={Wifi} label="Service" value={invoice.service?.service_number||'-'}/><InfoRow label="PPPoE" value={invoice.service?.pppoe_username||'-'}/><InfoRow label="Plan" value={invoice.service?.plan?.name||'-'}/><InfoRow label="Status" value={invoice.service?.status||'-'}/></div></Surface>
        <Surface title="Tanggal & Periode"><div className="space-y-3 text-sm"><InfoRow icon={CalendarDays} label="Period" value={`${date(invoice.period_start)} — ${date(invoice.period_end)}`}/><InfoRow label="Issued" value={date(invoice.issued_at)}/><InfoRow label="Due" value={date(invoice.due_at)}/><InfoRow label="Paid" value={invoice.paid_at?dateTime(invoice.paid_at):'-'}/></div></Surface>
      </section>

      <section className="jk-surface overflow-hidden"><div className="jk-surface-head"><h2 className="jk-surface-title">Invoice Items</h2><p className="jk-surface-subtitle">Rincian layanan yang membentuk nilai invoice.</p></div><div className="overflow-x-auto"><table className="min-w-[700px] w-full text-sm"><thead className="bg-slate-50 text-left text-[11px] font-extrabold uppercase tracking-wide text-slate-500"><tr><Th>Description</Th><Th>Qty</Th><Th>Unit Price</Th><Th>Amount</Th></tr></thead><tbody>{invoice.items?.map((i:any)=><tr key={i.id} className="border-t border-slate-100"><Td><div className="font-semibold text-slate-800">{i.description}</div><div className="mt-1 text-[11px] text-slate-400">{[i.meta?.service_number,i.meta?.plan_code].filter(Boolean).join(' · ')}</div></Td><Td>{i.quantity}</Td><Td>{rupiah(i.unit_price)}</Td><Td><span className="font-bold text-slate-900">{rupiah(i.amount)}</span></Td></tr>)}</tbody><tfoot className="border-t border-slate-200 bg-slate-50"><tr><td colSpan={3} className="px-4 py-2 text-right text-slate-500">Subtotal</td><td className="px-4 py-2 font-semibold">{rupiah(invoice.subtotal)}</td></tr><tr><td colSpan={3} className="px-4 py-2 text-right text-slate-500">Paid</td><td className="px-4 py-2 font-semibold text-emerald-700">{rupiah(invoice.paid_amount)}</td></tr><tr><td colSpan={3} className="px-4 py-3 text-right font-extrabold text-slate-800">Balance</td><td className="px-4 py-3 text-lg font-black text-slate-950">{rupiah(invoice.balance_due)}</td></tr></tfoot></table></div></section>

      <section className="grid gap-6 xl:grid-cols-2">
        <Surface title="Payment Gateway / QRIS" subtitle="Buat link pembayaran hanya jika Anda memiliki izin kelola billing.">{gateway?.enabled&&canPay?<div className="space-y-4"><div className="rounded-xl bg-blue-50 p-3 text-sm text-blue-800">Provider <b>{gateway.provider}</b> · {gateway.environment}</div><button onClick={()=>router.post(`/billing/invoices/${invoice.id}/gateway`,{}, {preserveScroll:true})} className="jk-btn primary"><Landmark size={16}/>Buat Link Pembayaran</button><div className="space-y-2">{invoice.gateway_transactions?.map((t:any)=><div key={t.id} className="rounded-xl border border-slate-200 p-3"><div className="flex justify-between gap-3"><div><div className="font-extrabold text-slate-800">{t.order_id}</div><div className="mt-1 text-xs text-slate-500">{t.provider} · {t.status} · {dateTime(t.created_at)}</div></div><div className="font-black">{rupiah(t.amount)}</div></div><div className="mt-3 flex flex-wrap gap-2">{t.redirect_url&&t.status==='pending'&&<a href={t.redirect_url} target="_blank" rel="noreferrer" className="jk-btn primary">Open Payment</a>}{t.provider==='midtrans'&&t.status==='pending'&&<button onClick={()=>router.post(`/billing/gateway-transactions/${t.id}/refresh`,{}, {preserveScroll:true})} className="jk-btn secondary">Refresh Status</button>}</div></div>)}{(!invoice.gateway_transactions||invoice.gateway_transactions.length===0)&&<EmptyState text="Belum ada payment link."/>}</div></div>:<div className="text-sm text-slate-500">{!canManage?'Anda memiliki akses lihat billing tanpa izin membuat payment gateway.':invoice.balance_due<=0?'Invoice tidak memiliki saldo yang dapat dibayar.':'Payment gateway belum aktif. Konfigurasikan di menu Integrations.'}</div>}</Surface>
        <Surface title="Payment Safety" subtitle="Kontrol posting pembayaran dan callback provider."><div className="space-y-3 text-sm leading-6 text-slate-600"><div className="flex gap-3"><ShieldCheck size={20} className="mt-0.5 shrink-0 text-emerald-600"/><p>Payment provider baru diposting setelah callback terverifikasi dan transaksi duplikat diproses secara idempotent.</p></div><div className="flex gap-3"><CreditCard size={20} className="mt-0.5 shrink-0 text-blue-600"/><p>Local mode menggunakan Mock QRIS untuk acceptance test tanpa uang nyata.</p></div></div></Surface>
      </section>

      <section className="grid gap-6 xl:grid-cols-2">
        <Surface title="Posting Pembayaran" subtitle="Pembayaran manual langsung hanya tersedia untuk role dengan billing.manage.">{canPay?<form className="space-y-3" onSubmit={e=>{e.preventDefault();form.post(`/billing/invoices/${invoice.id}/payments`,{preserveScroll:true,onSuccess:()=>{form.reset('reference','notes');form.setData('idempotency_key',idempotencyKey());}});}}><label className="block text-xs font-bold text-slate-500">Nominal<input className={`${input} mt-1`} type="number" min={1} max={invoice.balance_due} value={form.data.amount} onChange={e=>form.setData('amount',Number(e.target.value))}/>{form.errors.amount&&<span className="mt-1 block text-xs font-semibold text-rose-600">{form.errors.amount}</span>}</label><div className="grid gap-3 md:grid-cols-2"><select className={input} value={form.data.method} onChange={e=>form.setData('method',e.target.value)}>{paymentMethods.map(m=><option key={m} value={m}>{m.toUpperCase()}</option>)}</select><input className={input} type="datetime-local" value={form.data.paid_at} onChange={e=>form.setData('paid_at',e.target.value)}/></div><input className={input} value={form.data.reference} onChange={e=>form.setData('reference',e.target.value)} placeholder="Reference / nomor transfer (opsional)"/><textarea className={input} value={form.data.notes} onChange={e=>form.setData('notes',e.target.value)} placeholder="Catatan pembayaran" rows={3}/><button disabled={form.processing} className="jk-btn primary"><CircleDollarSign size={16}/>{form.processing?'Memproses...':'Posting Pembayaran'}</button></form>:<div className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600">{!canManage?'Mode read-only: Anda tidak memiliki izin posting pembayaran.':'Invoice tidak memiliki saldo yang dapat dibayar.'}</div>}</Surface>
        <Surface title="Riwayat Pembayaran" subtitle="Seluruh alokasi payment yang sudah masuk ke invoice."><div className="space-y-2">{invoice.allocations?.map((a:any)=><div key={a.id} className="rounded-xl border border-slate-200 p-3"><div className="flex justify-between gap-3"><div><div className="flex items-center gap-2 font-extrabold text-emerald-700"><History size={15}/>{a.payment?.payment_number}</div><div className="mt-1 text-xs text-slate-500">{a.payment?.method} · {a.payment?.reference||'tanpa referensi'}</div><div className="mt-1 text-[11px] text-slate-400">{dateTime(a.payment?.paid_at)} · oleh {a.payment?.creator?.name||'system'}</div>{a.payment?.id&&<a href={`/billing/payments/${a.payment.id}/receipt`} className="mt-2 inline-flex items-center gap-1 text-[11px] font-extrabold text-[var(--jk-primary)] hover:underline"><Download size={12}/>Receipt PDF</a>}</div><div className="font-black text-slate-900">{rupiah(a.amount)}</div></div></div>)}{(!invoice.allocations||invoice.allocations.length===0)&&<EmptyState text="Belum ada pembayaran."/>}</div></Surface>
      </section>
    </div>
  </Layout>;
}

function InfoRow({icon:Icon,label,value}:{icon?:React.ComponentType<{size?:number;className?:string}>;label:string;value:any}){return <div className="flex items-start justify-between gap-4 border-b border-slate-100 pb-2"><span className="flex items-center gap-2 text-slate-500">{Icon&&<Icon size={14} className="text-slate-400"/>}{label}</span><span className="max-w-[65%] text-right font-semibold text-slate-800">{String(value)}</span></div>}
function Th({children}:{children:React.ReactNode}){return <th className="px-4 py-3 font-extrabold">{children}</th>}
function Td({children}:{children:React.ReactNode}){return <td className="px-4 py-3 text-slate-600">{children}</td>}
function Status({value}:{value:string}){const cls=value==='paid'?'bg-emerald-50 text-emerald-700 ring-emerald-200':value==='overdue'?'bg-rose-50 text-rose-700 ring-rose-200':value==='partial'?'bg-amber-50 text-amber-700 ring-amber-200':value==='void'?'bg-slate-100 text-slate-600 ring-slate-200':'bg-blue-50 text-blue-700 ring-blue-200';return <span className={`inline-flex items-center rounded-full px-3 py-1.5 text-[10px] font-black uppercase ring-1 ${cls}`}>{value}</span>}
function rupiah(v:any){return 'Rp '+Number(v||0).toLocaleString('id-ID')}
function date(v?:string){return v?new Date(v+'T00:00:00').toLocaleDateString('id-ID'):'-'}
function dateTime(v?:string){return v?new Date(v).toLocaleString('id-ID'):'-'}
