import React from 'react';
import {Head, Link, router, useForm} from '@inertiajs/react';
import Layout from '../../components/Layout';

const input='w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm outline-none focus:border-sky-500';
const btn='rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold hover:bg-emerald-600 disabled:opacity-50';
const newPaymentKey=()=>globalThis.crypto.randomUUID();

export default function BillingShow({invoice,paymentMethods,gateway}:{invoice:any,paymentMethods:string[],gateway:any}){
  const form=useForm({amount:invoice.balance_due||0,method:'cash',reference:'',paid_at:new Date().toISOString().slice(0,16),notes:'',idempotency_key:newPaymentKey()});
  const canPay=invoice.balance_due>0&&!['void','paid'].includes(invoice.status);
  return <Layout>
    <Head title={invoice.invoice_number}/>
    <div className="space-y-6 max-w-6xl">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><Link href="/billing" className="text-xs text-sky-400">← Billing</Link><h2 className="text-2xl font-black mt-1">{invoice.invoice_number}</h2><div className="mt-2"><Status value={invoice.status}/></div></div><div className="text-right"><div className="text-xs uppercase text-slate-500">Sisa Tagihan</div><div className="text-3xl font-black">{rupiah(invoice.balance_due)}</div></div></div>

      <section className="grid lg:grid-cols-3 gap-4">
        <Card title="Pelanggan"><div className="space-y-2 text-sm"><Row label="Customer" value={`${invoice.customer?.customer_number} · ${invoice.customer?.name}`}/><Row label="Phone" value={invoice.customer?.phone||'-'}/><Row label="Email" value={invoice.customer?.email||'-'}/><Link href={`/customers/${invoice.customer?.id}`} className="inline-block text-sky-400 text-xs mt-2">Buka customer →</Link></div></Card>
        <Card title="Layanan"><div className="space-y-2 text-sm"><Row label="Service" value={invoice.service?.service_number||'-'}/><Row label="PPPoE" value={invoice.service?.pppoe_username||'-'}/><Row label="Plan" value={invoice.service?.plan?.name||'-'}/><Row label="Status" value={invoice.service?.status||'-'}/></div></Card>
        <Card title="Tanggal"><div className="space-y-2 text-sm"><Row label="Period" value={`${date(invoice.period_start)} — ${date(invoice.period_end)}`}/><Row label="Issued" value={date(invoice.issued_at)}/><Row label="Due" value={date(invoice.due_at)}/><Row label="Paid" value={invoice.paid_at?dateTime(invoice.paid_at):'-'}/></div></Card>
      </section>

      <section className="rounded-xl border border-slate-800 bg-slate-900/50 overflow-hidden"><div className="p-5 border-b border-slate-800"><h3 className="font-bold text-lg">Invoice Items</h3></div><div className="overflow-x-auto"><table className="min-w-[700px] w-full text-sm"><thead className="bg-slate-950/70 text-xs uppercase text-slate-500"><tr><Th>Description</Th><Th>Qty</Th><Th>Unit Price</Th><Th>Amount</Th></tr></thead><tbody>{invoice.items?.map((i:any)=><tr key={i.id} className="border-t border-slate-800"><Td>{i.description}<div className="text-[11px] text-slate-500">{i.meta?.service_number} · {i.meta?.plan_code}</div></Td><Td>{i.quantity}</Td><Td>{rupiah(i.unit_price)}</Td><Td>{rupiah(i.amount)}</Td></tr>)}</tbody><tfoot className="border-t border-slate-700"><tr><td colSpan={3} className="px-4 py-2 text-right text-slate-500">Subtotal</td><td className="px-4 py-2">{rupiah(invoice.subtotal)}</td></tr><tr><td colSpan={3} className="px-4 py-2 text-right text-slate-500">Paid</td><td className="px-4 py-2">{rupiah(invoice.paid_amount)}</td></tr><tr><td colSpan={3} className="px-4 py-3 text-right font-bold">Balance</td><td className="px-4 py-3 text-lg font-black">{rupiah(invoice.balance_due)}</td></tr></tfoot></table></div></section>

      <section className="grid xl:grid-cols-2 gap-6">
        <Card title="Payment Gateway / QRIS">{gateway?.enabled&&canPay?<div className="space-y-3"><div className="text-sm text-slate-400">Provider <b className="text-slate-200">{gateway.provider}</b> · {gateway.environment}</div><button onClick={()=>router.post(`/billing/invoices/${invoice.id}/gateway`,{}, {preserveScroll:true})} className="rounded-lg bg-sky-600 px-4 py-2 text-sm font-semibold hover:bg-sky-500">Buat Link Pembayaran</button><div className="space-y-2">{invoice.gateway_transactions?.map((t:any)=><div key={t.id} className="rounded-lg border border-slate-800 p-3"><div className="flex justify-between gap-3"><div><div className="font-semibold">{t.order_id}</div><div className="text-xs text-slate-500">{t.provider} · {t.status} · {dateTime(t.created_at)}</div></div><div className="font-bold">{rupiah(t.amount)}</div></div><div className="mt-2 flex flex-wrap gap-2">{t.redirect_url&&t.status==='pending'&&<a href={t.redirect_url} target="_blank" rel="noreferrer" className="rounded bg-emerald-700 px-3 py-1 text-xs font-semibold">Open Payment</a>}{t.provider==='midtrans'&&t.status==='pending'&&<button onClick={()=>router.post(`/billing/gateway-transactions/${t.id}/refresh`,{}, {preserveScroll:true})} className="rounded bg-slate-700 px-3 py-1 text-xs">Refresh Provider Status</button>}</div></div>)}{(!invoice.gateway_transactions||invoice.gateway_transactions.length===0)&&<div className="text-sm text-slate-500">Belum ada payment link.</div>}</div></div>:<div className="text-sm text-slate-500">{canPay?'Payment gateway belum aktif. Konfigurasikan di menu Integrations.':'Invoice tidak memiliki saldo yang dapat dibayar.'}</div>}</Card>
        <Card title="Payment Gateway Safety"><div className="space-y-2 text-sm text-slate-400"><p>Payment dari provider hanya diposting setelah callback terverifikasi. Callback duplikat diproses idempotently.</p><p>Local mode menggunakan Mock QRIS untuk acceptance test tanpa uang nyata.</p></div></Card>
      </section>

      <section className="grid xl:grid-cols-2 gap-6">
        <Card title="Posting Pembayaran">{canPay?<form className="space-y-3" onSubmit={e=>{e.preventDefault();form.post(`/billing/invoices/${invoice.id}/payments`,{preserveScroll:true,onSuccess:()=>{form.reset('reference','notes');form.setData('idempotency_key',newPaymentKey())}});}}><div><label className="text-xs text-slate-400">Nominal</label><input className={input} type="number" min={1} max={invoice.balance_due} value={form.data.amount} onChange={e=>form.setData('amount',Number(e.target.value))}/>{form.errors.amount&&<div className="text-xs text-rose-300 mt-1">{form.errors.amount}</div>}</div><div className="grid md:grid-cols-2 gap-3"><select className={input} value={form.data.method} onChange={e=>form.setData('method',e.target.value)}>{paymentMethods.map(m=><option key={m} value={m}>{m.toUpperCase()}</option>)}</select><input className={input} type="datetime-local" value={form.data.paid_at} onChange={e=>form.setData('paid_at',e.target.value)}/></div><input className={input} value={form.data.reference} onChange={e=>form.setData('reference',e.target.value)} placeholder="Reference / nomor transfer (opsional)"/><textarea className={input} value={form.data.notes} onChange={e=>form.setData('notes',e.target.value)} placeholder="Catatan pembayaran" rows={3}/><button disabled={form.processing} className={btn}>Posting Pembayaran</button></form>:<div className="rounded-lg bg-emerald-950/30 border border-emerald-900 p-4 text-sm text-emerald-200">Invoice tidak memiliki saldo yang dapat dibayar.</div>}</Card>
        <Card title="Riwayat Pembayaran"><div className="space-y-2">{invoice.allocations?.map((a:any)=><div key={a.id} className="rounded-lg border border-slate-800 p-3"><div className="flex justify-between gap-3"><div><div className="font-semibold text-emerald-300">{a.payment?.payment_number}</div><div className="text-xs text-slate-500">{a.payment?.method} · {a.payment?.reference||'no reference'}</div><div className="text-[11px] text-slate-600">{dateTime(a.payment?.paid_at)} · by {a.payment?.creator?.name||'system'}</div></div><div className="font-bold">{rupiah(a.amount)}</div></div></div>)}{(!invoice.allocations||invoice.allocations.length===0)&&<div className="text-sm text-slate-500">Belum ada pembayaran.</div>}</div></Card>
      </section>
    </div>
  </Layout>;
}

function Card({title,children}:{title:string,children:React.ReactNode}){return <section className="rounded-xl border border-slate-800 bg-slate-900/50 p-5"><h3 className="font-bold text-lg mb-4">{title}</h3>{children}</section>}
function Row({label,value}:{label:string,value:any}){return <div className="flex justify-between gap-4 border-b border-slate-800 pb-2"><span className="text-slate-500">{label}</span><span className="text-right font-medium">{String(value)}</span></div>}
function Th({children}:{children:React.ReactNode}){return <th className="text-left px-4 py-3 font-semibold">{children}</th>}
function Td({children}:{children:React.ReactNode}){return <td className="px-4 py-3">{children}</td>}
function Status({value}:{value:string}){const cls=value==='paid'?'bg-emerald-950 text-emerald-200':value==='overdue'?'bg-rose-950 text-rose-200':value==='partial'?'bg-amber-950 text-amber-200':'bg-sky-950 text-sky-200';return <span className={`rounded px-2 py-1 text-xs uppercase ${cls}`}>{value}</span>}
function rupiah(v:any){return 'Rp'+Number(v||0).toLocaleString('id-ID')}
function date(v?:string){return v?new Date(v+'T00:00:00').toLocaleDateString('id-ID'):'-'}
function dateTime(v?:string){return v?new Date(v).toLocaleString('id-ID'):'-'}
