import React, {FormEvent, useState} from 'react';
import {Head, Link, router} from '@inertiajs/react';
import Layout from '../../components/Layout';

const input='rounded-lg border border-slate-300 bg-slate-50 px-3 py-2 text-sm outline-none focus:border-sky-500';

export default function Reports({report,filters,exports=[]}:{report:any,filters:{from:string,to:string},exports:any[]}){
  const [from,setFrom]=useState(filters.from); const [to,setTo]=useState(filters.to);
  const apply=(e:FormEvent)=>{e.preventDefault();router.get('/reports',{from,to},{preserveState:true,replace:true});};
  const exportUrl=(type:string)=>`/reports/export/${type}?from=${encodeURIComponent(filters.from)}&to=${encodeURIComponent(filters.to)}`;
  return <Layout><Head title="Analytics & Reports"/><div className="space-y-6">
    <div className="flex flex-col xl:flex-row xl:items-end justify-between gap-4"><div><h2 className="text-2xl font-black">Analytics & Reports</h2><p className="text-sm text-slate-500 mt-1">Laporan revenue, collection, customer growth, outstanding aging, traffic, dan automation.</p></div><form onSubmit={apply} className="flex flex-wrap gap-2 items-end"><label className="text-xs text-slate-500">Dari<input type="date" className={`${input} block mt-1`} value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-xs text-slate-500">Sampai<input type="date" className={`${input} block mt-1`} value={to} onChange={e=>setTo(e.target.value)}/></label><button className="rounded-lg bg-sky-600 px-4 py-2 text-sm font-semibold hover:bg-sky-500">Terapkan</button></form></div>

    <section className="grid grid-cols-2 xl:grid-cols-5 gap-3"><Metric title="Pelanggan" value={num(report.summary.customers_total)} hint={`+${num(report.summary.customers_new)} periode ini`}/><Metric title="Layanan Aktif" value={num(report.summary.services_active)} hint={`${num(report.summary.services_suspended)} suspended`}/><Metric title="Invoiced" value={rupiah(report.summary.invoiced)} hint={`${num(report.summary.invoice_count)} invoice`}/><Metric title="Payments" value={rupiah(report.summary.payments)} hint={`Collection ${Number(report.summary.collection_rate||0).toLocaleString('id-ID')}%`}/><Metric title="Outstanding" value={rupiah(report.summary.outstanding)}/></section>

    <section className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3 mb-4"><div><h3 className="font-bold text-lg">Export CSV</h3><p className="text-xs text-slate-500">UTF-8 CSV dengan audit riwayat export.</p></div><div className="flex flex-wrap gap-2">{[['customers','Customers'],['services','Services'],['invoices','Invoices'],['outstanding','Outstanding'],['payments','Payments'],['sessions','Online Sessions']].map(([k,n])=><a key={k} href={exportUrl(k)} className="rounded-lg border border-slate-300 px-3 py-2 text-xs hover:border-sky-600">{n}</a>)}</div></div><div className="text-[11px] text-slate-500">Periode filter diterapkan pada invoice dan payment. Outstanding adalah snapshot seluruh saldo terbuka saat ini; customer/service adalah master terkini; sessions hanya session online.</div></section>

    <section className="grid xl:grid-cols-2 gap-6"><Card title="Financial Trend"><Financial rows={report.financial}/></Card><Card title="Customer Growth"><Bars rows={report.customer_growth.map((r:any)=>({label:periodLabel(r.period),value:r.total,text:num(r.total)}))}/></Card></section>
    <section className="grid xl:grid-cols-3 gap-6"><Card title="Status Layanan"><Bars rows={report.service_status.map((r:any)=>({label:String(r.status).replaceAll('_',' '),value:r.total,text:num(r.total)}))}/></Card><Card title="Paket Terpasang"><Bars rows={report.plan_distribution.map((r:any)=>({label:`${r.code} · ${r.name}`,value:r.total,text:num(r.total)}))}/></Card><Card title="Outstanding Aging"><div className="space-y-2">{report.aging.map((a:any)=><div key={a.bucket} className="rounded-lg border border-slate-200 p-3"><div className="flex justify-between"><span className="font-medium">{a.label}</span><span className="font-bold">{rupiah(a.amount)}</span></div><div className="text-xs text-slate-500 mt-1">{a.invoices} invoice</div></div>)}</div></Card></section>

    <section className="grid xl:grid-cols-2 gap-6"><Card title="Top Outstanding Customer"><TableOutstanding rows={report.top_outstanding}/></Card><Card title="Top Data Usage"><div className="mb-4 text-2xl font-black text-blue-700">{bytes(report.network.traffic_period_bytes)}</div><div className="space-y-2">{report.network.top_usage.map((r:any)=><div key={r.id} className="rounded-lg border border-slate-200 p-3 flex justify-between gap-4"><div><div className="font-medium">{r.customer_number} · {r.customer_name}</div><div className="text-xs text-slate-500">{r.service_number} · {r.pppoe_username}</div></div><div className="font-bold">{bytes(r.bytes)}</div></div>)}{report.network.top_usage.length===0&&<Empty text="Belum ada accounting data pada periode ini."/>}</div></Card></section>

    <section className="grid xl:grid-cols-2 gap-6"><Card title="Automation Events"><div className="space-y-2">{report.automation.events.map((r:any)=><div key={r.event} className="rounded-lg border border-slate-200 p-3 flex justify-between"><div><div className="font-medium">{r.event}</div><div className="text-xs text-slate-500">success {r.success}/{r.total}</div></div><div className="font-bold">{r.total}</div></div>)}{report.automation.events.length===0&&<Empty text="Belum ada automation event pada periode ini."/>}</div></Card><Card title="Automation Terbaru"><div className="space-y-2 max-h-[430px] overflow-auto">{report.automation.recent.map((r:any)=><div key={r.id} className="rounded-lg border border-slate-200 p-3"><div className="flex justify-between gap-3"><div className="font-medium">{r.event}</div><span className={`text-[10px] rounded px-2 py-1 ${r.success?'bg-emerald-50 text-emerald-200':'bg-rose-50 text-rose-200'}`}>{r.success?'OK':'FAIL'}</span></div><div className="text-xs text-slate-500 mt-1">{r.customer_number||'-'} · {r.name||'-'} · {r.service_number||'-'}</div><div className="text-[11px] text-slate-500 mt-1">{r.message||'-'} · {dateTime(r.created_at)}</div></div>)}{report.automation.recent.length===0&&<Empty text="Belum ada event."/>}</div></Card></section>

    <Card title="Riwayat Export"><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-sm"><thead className="text-xs uppercase text-slate-500"><tr><Th>Waktu</Th><Th>Report</Th><Th>Rows</Th><Th>User</Th><Th>Filter</Th></tr></thead><tbody>{exports.map((x:any)=><tr key={x.id} className="border-t border-slate-200"><Td>{dateTime(x.exported_at)}</Td><Td className="uppercase">{x.report_type}</Td><Td>{x.row_count}</Td><Td>{x.exporter?.email||'-'}</Td><Td>{x.filters?.from||'-'} → {x.filters?.to||'-'}</Td></tr>)}{exports.length===0&&<tr><td colSpan={5} className="p-6 text-center text-slate-500">Belum ada export.</td></tr>}</tbody></table></div></Card>
  </div></Layout>;
}

function Card({title,children}:{title:string,children:React.ReactNode}){return <section className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold text-lg mb-4">{title}</h3>{children}</section>}
function Metric({title,value,hint}:{title:string,value:any,hint?:string}){return <div className="rounded-xl border border-slate-200 bg-white p-4"><div className="text-[10px] uppercase tracking-wider text-slate-500">{title}</div><div className="text-xl font-black mt-1 break-words">{String(value)}</div>{hint&&<div className="text-[11px] text-slate-500 mt-1">{hint}</div>}</div>}
function Financial({rows}:{rows:any[]}){const max=Math.max(1,...rows.flatMap(r=>[Number(r.invoiced),Number(r.payments)]));return <div className="space-y-3">{rows.map(r=><div key={r.period}><div className="flex justify-between text-xs mb-1"><span>{periodLabel(r.period)}</span><span className="text-slate-500">paid {rupiah(r.payments)} · invoice {rupiah(r.invoiced)}</span></div><div className="h-3 bg-slate-50 rounded relative overflow-hidden"><div className="absolute inset-y-0 left-0 bg-slate-700" style={{width:`${Number(r.invoiced)/max*100}%`}}/><div className="absolute inset-y-0 left-0 bg-emerald-500/80" style={{width:`${Number(r.payments)/max*100}%`}}/></div></div>)}</div>}
function Bars({rows}:{rows:{label:string,value:number,text:string}[]}){const max=Math.max(1,...rows.map(r=>Number(r.value)));return <div className="space-y-3">{rows.map((r,i)=><div key={`${r.label}-${i}`}><div className="flex justify-between gap-3 text-xs mb-1"><span className="capitalize truncate">{r.label}</span><span>{r.text}</span></div><div className="h-2 rounded bg-slate-50 overflow-hidden"><div className="h-full bg-sky-500/75" style={{width:`${Number(r.value)/max*100}%`}}/></div></div>)}{rows.length===0&&<Empty text="Belum ada data."/>}</div>}
function TableOutstanding({rows}:{rows:any[]}){return <div className="space-y-2">{rows.map(r=><Link href={`/customers/${r.id}`} key={r.id} className="block rounded-lg border border-slate-200 p-3 hover:border-sky-700"><div className="flex justify-between gap-4"><div><div className="font-medium">{r.customer_number} · {r.name}</div><div className="text-xs text-slate-500">{r.invoices} open invoice</div></div><div className="font-bold">{rupiah(r.outstanding)}</div></div></Link>)}{rows.length===0&&<Empty text="Tidak ada outstanding."/>}</div>}
function Empty({text}:{text:string}){return <div className="text-sm text-slate-500">{text}</div>}
function Th({children}:{children:React.ReactNode}){return <th className="text-left py-2 pr-4">{children}</th>}
function Td({children,className=''}:{children:React.ReactNode,className?:string}){return <td className={`py-3 pr-4 ${className}`}>{children}</td>}
function rupiah(v:any){return 'Rp'+Number(v||0).toLocaleString('id-ID')}
function num(v:any){return Number(v||0).toLocaleString('id-ID')}
function bytes(v:any){let n=Number(v||0);for(const u of ['B','KB','MB','GB','TB','PB']){if(n<1024||u==='PB')return `${n.toLocaleString('id-ID',{maximumFractionDigits:n<10?2:1})} ${u}`;n/=1024}return '-'}
function periodLabel(v:string){const [y,m]=v.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('id-ID',{month:'short',year:'2-digit'})}
function dateTime(v?:string){return v?new Date(v).toLocaleString('id-ID'):'-'}
