import React,{useMemo,useState} from 'react';
import {Head,usePage} from '@inertiajs/react';
import {Boxes,Building2,ExternalLink,Network,ShieldCheck,UsersRound} from 'lucide-react';
export default function Access({tenants=[],defaultTenantSlug=''}:any){
  const page:any=usePage().props;const b=page.branding||{};const primary=b.primary_color||'#0f6cbd';
  const [slug,setSlug]=useState(defaultTenantSlug||tenants?.[0]?.slug||'');
  const selected=useMemo(()=>tenants.find((t:any)=>t.slug===slug),[tenants,slug]);
  const go=(type:string)=>{if(type==='admin'){window.location.href='/login';return;}const s=slug.trim();if(!s)return;const path=type==='customer'?`/portal/${encodeURIComponent(s)}/login`:type==='partner'?`/mitra/${encodeURIComponent(s)}/login`:`/inventory/${encodeURIComponent(s)}/login`;window.location.href=path;};
  return <div className="min-h-screen bg-slate-50 p-5 text-slate-900"><Head title={`Pusat Akses · ${b.app_name||'Jaringanku'}`}/><div className="mx-auto max-w-6xl py-8 md:py-14">
    <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-[0_20px_60px_rgba(15,23,42,.07)] md:p-10">
      <div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-2xl">{b.logo_url?<img src={b.logo_url} className="h-12 max-w-56 object-contain"/>:<div className="text-3xl font-black tracking-tight" style={{color:primary}}>{b.app_name||'JARINGANKU'}</div>}<h1 className="mt-5 text-3xl font-black tracking-tight md:text-4xl">Pilih portal sesuai pekerjaan Anda.</h1><p className="mt-3 text-sm leading-6 text-slate-500">Satu pusat akses untuk Admin ISP, pelanggan, mitra/reseller dan tim inventory. Portal tenant membutuhkan kode ISP yang aktif.</p></div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 lg:w-80"><label className="text-xs font-black uppercase tracking-wide text-slate-500">Kode ISP / Tenant</label>{tenants.length>0?<select value={slug} onChange={e=>setSlug(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm"><option value="">Pilih ISP</option>{tenants.map((t:any)=><option key={t.slug} value={t.slug}>{t.name} ({t.slug})</option>)}</select>:<input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="kode-isp" className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm"/>}<div className="mt-2 text-xs text-slate-500">{selected?`Tenant aktif: ${selected.name}`:'Masukkan kode tenant yang diberikan ISP.'}</div></div></div>
      <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Card icon={ShieldCheck} title="Admin ISP" desc="Pelanggan, billing, jaringan, laporan dan konfigurasi tenant." onClick={()=>go('admin')} enabled/><Card icon={Building2} title="Customer Portal" desc="Tagihan, pembayaran, layanan internet dan ticket bantuan." onClick={()=>go('customer')} enabled={Boolean(slug.trim())}/><Card icon={UsersRound} title="Portal Mitra" desc="Pelanggan area mitra, billing, komisi dan operasional." onClick={()=>go('partner')} enabled={Boolean(slug.trim())}/><Card icon={Boxes} title="Portal Inventory" desc="Warehouse, stok teknisi, asset, transfer dan stock opname." onClick={()=>go('inventory')} enabled={Boolean(slug.trim())}/></div>
      <div className="mt-8 flex items-center justify-center gap-2 text-xs text-slate-400"><Network size={14}/>Akses portal dipisahkan untuk menjaga keamanan dan ruang kerja setiap role.</div>
    </div>
  </div></div>;
}
function Card({icon:Icon,title,desc,onClick,enabled}:any){return <button disabled={!enabled} onClick={onClick} className="group rounded-2xl border border-slate-200 bg-white p-5 text-left transition hover:-translate-y-0.5 hover:border-[var(--auth-primary,#0f6cbd)] hover:shadow-lg disabled:cursor-not-allowed disabled:opacity-45"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-[#0f6cbd]"><Icon size={22}/></div><div className="mt-4 flex items-center justify-between font-black"><span>{title}</span><ExternalLink size={16} className="text-slate-300 transition group-hover:text-[#0f6cbd]"/></div><p className="mt-2 text-sm leading-6 text-slate-500">{desc}</p></button>}
