import React,{FormEvent,useMemo,useState} from 'react';
import {Head} from '@inertiajs/react';
import {Boxes,Building2,ExternalLink,ShieldCheck,UsersRound} from 'lucide-react';
export default function Access({tenants=[],defaultTenantSlug=''}:any){
  const [slug,setSlug]=useState(defaultTenantSlug||tenants?.[0]?.slug||'');
  const selected=useMemo(()=>tenants.find((t:any)=>t.slug===slug),[tenants,slug]);
  const go=(type:string)=>{if(type==='admin'){window.location.href='/login';return;}const s=slug.trim();if(!s)return;const path=type==='customer'?`/portal/${encodeURIComponent(s)}/login`:type==='partner'?`/mitra/${encodeURIComponent(s)}/login`:`/inventory/${encodeURIComponent(s)}/login`;window.location.href=path;};
  return <div className="min-h-screen bg-[#f5f7fb] p-5 text-slate-900"><Head title="Pusat Akses Jaringanku"/><div className="mx-auto max-w-6xl py-8 md:py-16"><div className="text-center"><div className="text-3xl font-black tracking-tight text-[#0f6cbd]">JARINGANKU</div><h1 className="mt-4 text-3xl font-black">Pusat Akses</h1><p className="mx-auto mt-2 max-w-2xl text-slate-500">Tidak perlu menghafal URL portal. Masukkan kode ISP/tenant lalu pilih portal yang ingin dibuka.</p></div><div className="mx-auto mt-8 max-w-2xl rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label className="text-sm font-semibold">Kode ISP / Tenant</label>{tenants.length>0?<select value={slug} onChange={e=>setSlug(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3"><option value="">Pilih ISP</option>{tenants.map((t:any)=><option key={t.slug} value={t.slug}>{t.name} ({t.slug})</option>)}</select>:<input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="contoh: demo-isp" className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3"/>}<div className="mt-2 text-xs text-slate-500">{selected?`Terpilih: ${selected.name}`:'Kode ini diberikan oleh administrator ISP.'}</div></div><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Card icon={ShieldCheck} title="Admin ISP" desc="Billing, pelanggan, jaringan, laporan dan konfigurasi." onClick={()=>go('admin')}/><Card icon={Building2} title="Customer Portal" desc="Tagihan, pembayaran, layanan dan tiket pelanggan." onClick={()=>go('customer')}/><Card icon={UsersRound} title="Portal Mitra" desc="Pelanggan mitra, billing, komisi dan operasional." onClick={()=>go('partner')}/><Card icon={Boxes} title="Portal Inventory" desc="Gudang, stok teknisi, asset, transfer dan opname." onClick={()=>go('inventory')}/></div><div className="mt-8 text-center text-xs text-slate-400">Jika portal menampilkan tenant tidak ditemukan, pastikan kode ISP benar dan tenant aktif.</div></div></div>;
}
function Card({icon:Icon,title,desc,onClick}:any){return <button onClick={onClick} className="group rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-[#0f6cbd] hover:shadow-md"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-[#0f6cbd]"><Icon size={22}/></div><div className="mt-4 flex items-center justify-between font-bold"><span>{title}</span><ExternalLink size={16} className="text-slate-400 group-hover:text-[#0f6cbd]"/></div><p className="mt-2 text-sm leading-6 text-slate-500">{desc}</p></button>}
