import React from 'react';
import {Head, Link} from '@inertiajs/react';
import {Activity, AlertTriangle, ArrowRight, CircleDollarSign, FileText, Router as RouterIcon, UserPlus, Users, Wifi} from 'lucide-react';
import Layout from '../components/Layout';

type MoneyPoint={period:string;invoiced:number;payments:number;balance:number};
type GrowthPoint={period:string;total:number};
type Aging={bucket:string;label:string;invoices:number;amount:number};
type Usage={id:number;service_number:string;pppoe_username:string;customer_number:string;customer_name:string;bytes:number};
type Outstanding={id:number;customer_number:string;name:string;invoices:number;outstanding:number};

export default function Dashboard({kpis={},financial=[],customer_growth=[],service_status=[],aging=[],top_outstanding=[],top_usage=[]}:{kpis:any;financial:MoneyPoint[];customer_growth:GrowthPoint[];service_status:any[];aging:Aging[];top_outstanding:Outstanding[];top_usage:Usage[]}){
  return <Layout><Head title="Dashboard"/><div className="space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-xs font-bold uppercase tracking-[.16em] text-blue-600">Ringkasan Operasional</div><h1 className="mt-1 text-2xl font-black tracking-tight text-slate-950">Dashboard ISP</h1><p className="mt-1 text-sm text-slate-500">Angka penting billing, pelanggan dan jaringan dalam satu layar agar tim cepat menentukan tindakan.</p></div><div className="flex flex-wrap gap-2"><Link href="/customers" className="inline-flex items-center gap-2 rounded-xl bg-[var(--jk-primary)] px-4 py-2.5 text-sm font-bold text-white"><UserPlus size={16}/> Tambah Pelanggan</Link><Link href="/billing" className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold"><FileText size={16}/> Buka Billing</Link></div></header>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
      <Kpi icon={Users} label="Total Pelanggan" value={num(kpis.customers)} sub={`+${num(kpis.new_customers_month)} bulan ini`} tone="blue"/>
      <Kpi icon={Wifi} label="Layanan Aktif" value={num(kpis.active_services)} sub={`${num(kpis.suspended_services)} terisolir/suspended`} tone="emerald"/>
      <Kpi icon={Activity} label="Pelanggan Online" value={num(kpis.online_sessions)} sub={`${num(kpis.routers_down)} router tidak online`} tone="cyan"/>
      <Kpi icon={CircleDollarSign} label="Pendapatan Bulan Ini" value={rupiah(kpis.revenue_month)} sub={`Invoice ${rupiah(kpis.invoiced_month)}`} tone="amber"/>
      <Kpi icon={AlertTriangle} label="Outstanding" value={rupiah(kpis.outstanding)} sub={`Collection ${Number(kpis.collection_rate||0).toLocaleString('id-ID')}%`} tone="rose"/>
    </section>

    <section className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]">
      <Card title="Billing vs Pembayaran — 6 Bulan" subtitle="Bandingkan nilai invoice terbit dengan pembayaran yang sudah benar-benar terposting."><MoneyBars rows={financial}/></Card>
      <Card title="Aksi Cepat" subtitle="Menu yang paling sering digunakan staf billing dan operasional."><div className="grid gap-2 sm:grid-cols-2"><Quick href="/billing/manual-payments" title="Review Bukti Bayar" text="Approve/reject transfer & QRIS manual"/><Quick href="/operations" title="Automation & Isolir" text="Cek overdue, isolir dan reaktivasi"/><Quick href="/partners" title="Mitra / Reseller" text="Kelola mitra, komisi dan pelanggan"/><Quick href="/inventory-management" title="Inventory" text="Gudang, asset dan stok teknisi"/><Quick href="/access" title="Pusat Akses Portal" text="Customer, Mitra dan Inventory"/><Quick href="/settings" title="Branding & User" text="Logo, QRIS, role dan permission"/></div></Card>
    </section>

    <section className="grid gap-6 xl:grid-cols-3">
      <Card title="Status Layanan"><StatusList rows={service_status}/></Card>
      <Card title="Umur Piutang"><div className="space-y-2">{aging.map(a=><div key={a.bucket} className="flex items-center justify-between gap-3 rounded-xl border border-slate-100 bg-slate-50/60 p-3"><div><div className="text-sm font-semibold">{a.label}</div><div className="text-xs text-slate-400">{a.invoices} invoice</div></div><div className="text-sm font-black">{rupiah(a.amount)}</div></div>)}{!aging.length&&<Empty text="Belum ada aging outstanding."/>}</div></Card>
      <Card title="Traffic Pelanggan" subtitle={`Total periode ${bytes(kpis.traffic_period_bytes)}`}><div className="space-y-2">{top_usage.slice(0,6).map(x=><div key={x.id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-100 p-3"><div className="min-w-0"><div className="truncate text-sm font-semibold">{x.customer_name}</div><div className="truncate text-xs text-slate-400">{x.customer_number} · {x.pppoe_username}</div></div><div className="whitespace-nowrap text-sm font-bold">{bytes(x.bytes)}</div></div>)}{!top_usage.length&&<Empty text="Belum ada data RADIUS accounting pada periode ini."/>}</div></Card>
    </section>

    <Card title="Pelanggan Prioritas Penagihan" subtitle="Outstanding terbesar yang sebaiknya ditindaklanjuti lebih dulu."><div className="overflow-x-auto"><table className="min-w-[720px] w-full text-sm"><thead className="bg-slate-50 text-left text-[11px] font-bold uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Pelanggan</th><th className="px-4 py-3">Invoice Belum Lunas</th><th className="px-4 py-3">Outstanding</th><th className="px-4 py-3 text-right">Aksi</th></tr></thead><tbody>{top_outstanding.map(x=><tr key={x.id} className="border-t border-slate-100"><td className="px-4 py-3"><div className="font-semibold">{x.name}</div><div className="text-xs text-blue-600">{x.customer_number}</div></td><td className="px-4 py-3">{x.invoices}</td><td className="px-4 py-3 font-black">{rupiah(x.outstanding)}</td><td className="px-4 py-3 text-right"><Link href={`/customers/${x.id}`} className="inline-flex items-center gap-1 text-xs font-bold text-blue-600">Detail <ArrowRight size={13}/></Link></td></tr>)}{!top_outstanding.length&&<tr><td colSpan={4} className="p-10 text-center text-slate-400">Tidak ada outstanding.</td></tr>}</tbody></table></div></Card>
  </div></Layout>;
}

function Card({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}){return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold text-slate-950">{title}</h2>{subtitle&&<p className="mt-1 text-xs text-slate-400">{subtitle}</p>}</div><div className="p-5">{children}</div></section>}
function Kpi({icon:Icon,label,value,sub,tone}:any){const map:any={blue:'bg-blue-50 text-blue-600',emerald:'bg-emerald-50 text-emerald-600',cyan:'bg-cyan-50 text-cyan-600',amber:'bg-amber-50 text-amber-600',rose:'bg-rose-50 text-rose-600'};return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="text-[11px] font-bold uppercase tracking-wide text-slate-400">{label}</div><div className="mt-1 break-words text-xl font-black text-slate-950">{value}</div><div className="mt-1 text-xs text-slate-400">{sub}</div></div><div className={`rounded-xl p-2.5 ${map[tone]}`}><Icon size={19}/></div></div></div>}
function Quick({href,title,text}:{href:string;title:string;text:string}){return <Link href={href} className="group rounded-xl border border-slate-200 p-3 transition hover:border-blue-300 hover:bg-blue-50/40"><div className="flex items-center justify-between gap-2 text-sm font-bold text-slate-800"><span>{title}</span><ArrowRight size={14} className="text-slate-300 group-hover:text-blue-600"/></div><div className="mt-1 text-xs leading-5 text-slate-400">{text}</div></Link>}
function MoneyBars({rows}:{rows:MoneyPoint[]}){const max=Math.max(1,...rows.flatMap(r=>[r.invoiced,r.payments]));return <div className="space-y-4">{rows.map(r=><div key={r.period}><div className="mb-1.5 flex justify-between gap-3 text-xs"><span className="font-semibold">{periodLabel(r.period)}</span><span className="text-slate-400">Bayar {rupiah(r.payments)} / Invoice {rupiah(r.invoiced)}</span></div><div className="relative h-3 overflow-hidden rounded-full bg-slate-100"><div className="absolute inset-y-0 left-0 rounded-full bg-blue-200" style={{width:`${r.invoiced/max*100}%`}}/><div className="absolute inset-y-0 left-0 rounded-full bg-emerald-500" style={{width:`${r.payments/max*100}%`}}/></div></div>)}{!rows.length&&<Empty text="Belum ada data billing."/>}<div className="flex gap-4 text-[11px] text-slate-400"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-blue-200"/>Invoice</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-emerald-500"/>Pembayaran</span></div></div>}
function StatusList({rows}:{rows:any[]}){const total=Math.max(1,rows.reduce((a,r)=>a+Number(r.total||0),0));return <div className="space-y-3">{rows.map(r=><div key={r.status}><div className="mb-1 flex justify-between text-sm"><span className="font-medium">{statusLabel(r.status)}</span><span className="font-bold">{r.total}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-500" style={{width:`${Number(r.total)/total*100}%`}}/></div></div>)}{!rows.length&&<Empty text="Belum ada layanan."/>}</div>}
function Empty({text}:{text:string}){return <div className="py-5 text-center text-sm text-slate-400">{text}</div>}
function rupiah(v:any){return 'Rp'+Number(v||0).toLocaleString('id-ID')}
function num(v:any){return Number(v||0).toLocaleString('id-ID')}
function bytes(v:any){let n=Number(v||0);for(const u of ['B','KB','MB','GB','TB','PB']){if(n<1024||u==='PB')return `${n.toLocaleString('id-ID',{maximumFractionDigits:n<10?2:1})} ${u}`;n/=1024}return '-'}
function periodLabel(v:string){const [y,m]=v.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('id-ID',{month:'short',year:'numeric'})}
function statusLabel(v:string){const x=v.replaceAll('_',' ');return x.charAt(0).toUpperCase()+x.slice(1)}
