import React, {FormEvent, useState} from 'react';
import {Head, router, useForm} from '@inertiajs/react';
import Layout from '../../components/Layout';

const money=(v:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v||0);
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="font-semibold mb-4">{title}</h2>{children}</section>}

export default function PlatformIndex(props:any){
  const plans=props.plans||[];
  const create=useForm({name:'',slug:'',owner_name:'',owner_email:'',owner_password:'',platform_plan_id:plans[0]?.id||''});
  const submit=(e:FormEvent)=>{e.preventDefault();create.post('/platform/tenants',{preserveScroll:true,onSuccess:()=>create.reset('name','slug','owner_name','owner_email','owner_password')});};
  return <Layout><div className="mb-4 flex justify-end"><a href="/platform/release" className="rounded bg-violet-700 px-3 py-2 text-sm">Release & Security Audit</a></div><Head title="Platform SaaS"/><div className="space-y-6">
    <div><h1 className="text-2xl font-bold">Platform SaaS · Jaringanku v{props.release?.version}</h1><p className="text-sm text-slate-400">Control plane tenant, subscription, quota, dan release production.</p></div>
    <div className="grid md:grid-cols-5 gap-3">{Object.entries(props.stats||{}).map(([k,v]:any)=><div key={k} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="text-xs uppercase text-slate-500">{k.replaceAll('_',' ')}</div><div className="text-2xl font-bold mt-1">{v}</div></div>)}</div>
    <div className="grid xl:grid-cols-2 gap-6">
      <Card title="Buat tenant baru"><form onSubmit={submit} className="space-y-3"><div className="grid md:grid-cols-2 gap-3"><input className="rounded bg-slate-950 border border-slate-700 p-2" placeholder="Nama ISP" value={create.data.name} onChange={e=>create.setData('name',e.target.value)}/><input className="rounded bg-slate-950 border border-slate-700 p-2" placeholder="slug-isp" value={create.data.slug} onChange={e=>create.setData('slug',e.target.value)}/><input className="rounded bg-slate-950 border border-slate-700 p-2" placeholder="Nama owner" value={create.data.owner_name} onChange={e=>create.setData('owner_name',e.target.value)}/><input className="rounded bg-slate-950 border border-slate-700 p-2" placeholder="owner@example.com" value={create.data.owner_email} onChange={e=>create.setData('owner_email',e.target.value)}/><input type="password" className="rounded bg-slate-950 border border-slate-700 p-2" placeholder="Password minimal 12 karakter" value={create.data.owner_password} onChange={e=>create.setData('owner_password',e.target.value)}/><select className="rounded bg-slate-950 border border-slate-700 p-2" value={create.data.platform_plan_id} onChange={e=>create.setData('platform_plan_id',Number(e.target.value))}>{plans.map((p:any)=><option key={p.id} value={p.id}>{p.name} · {money(p.monthly_price)}</option>)}</select></div><button disabled={create.processing} className="rounded bg-sky-600 px-4 py-2">Create tenant + 14 hari trial</button></form></Card>
      <Card title="SaaS plans"><div className="grid sm:grid-cols-2 gap-3">{plans.map((p:any)=><div key={p.id} className="rounded-lg border border-slate-800 p-3"><div className="font-semibold">{p.name} <span className="text-xs text-slate-500">{p.code}</span></div><div className="text-sky-300">{p.monthly_price?money(p.monthly_price)+'/bln':'Custom'}</div><div className="text-xs text-slate-400 mt-2">Customers {p.max_customers??'∞'} · Services {p.max_services??'∞'} · Routers {p.max_routers??'∞'} · Users {p.max_users??'∞'}</div></div>)}</div></Card>
    </div>
    <Card title="Tenants & subscriptions"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="text-slate-400"><tr><th className="p-2 text-left">Tenant</th><th className="p-2 text-left">Plan</th><th className="p-2 text-left">Usage</th><th className="p-2 text-left">Status</th><th className="p-2 text-right">Action</th></tr></thead><tbody>{(props.tenants||[]).map((t:any)=><TenantRow key={t.id} tenant={t} plans={plans}/>)}</tbody></table></div></Card>
    <div className="grid xl:grid-cols-2 gap-6"><Card title="Platform events"><div className="max-h-80 overflow-auto space-y-2">{(props.events||[]).map((e:any)=><div key={e.id} className="border-b border-slate-800 pb-2"><div>{e.event} <span className="text-xs text-slate-500">{e.tenant?.name||'platform'}</span></div><div className="text-xs text-slate-500">{e.user?.email||'system'} · {e.created_at}</div></div>)}</div></Card><Card title="Release history"><div className="max-h-80 overflow-auto space-y-2">{(props.releases||[]).map((r:any)=><div key={r.id} className="border-b border-slate-800 pb-2"><div className="font-medium">v{r.version} · {r.environment} · {r.status}</div><div className="text-xs text-slate-500">schema {r.schema_version||'-'} · {r.deployed_at||r.created_at}</div></div>)}{(props.releases||[]).length===0&&<div className="text-slate-500">Belum ada release record.</div>}</div></Card></div>
  </div></Layout>
}

function TenantRow({tenant,plans}:{tenant:any;plans:any[]}){
  const [plan,setPlan]=useState(tenant.subscription?.plan?.id||plans[0]?.id); const [status,setStatus]=useState(tenant.subscription?.status||'active');
  const save=()=>router.put(`/platform/tenants/${tenant.id}/subscription`,{platform_plan_id:plan,status,period_days:30},{preserveScroll:true});
  const tenantStatus=(v:string)=>router.put(`/platform/tenants/${tenant.id}/status`,{status:v},{preserveScroll:true});
  return <tr className="border-t border-slate-800"><td className="p-2"><div className="font-medium">{tenant.name}</div><div className="text-xs text-slate-500">{tenant.slug}</div></td><td className="p-2"><select className="rounded bg-slate-950 border border-slate-700 p-1" value={plan} onChange={e=>setPlan(Number(e.target.value))}>{plans.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></td><td className="p-2 text-xs">C {tenant.usage?.customers||0} · S {tenant.usage?.services||0} · R {tenant.usage?.routers||0} · U {tenant.usage?.users||0}</td><td className="p-2"><select className="rounded bg-slate-950 border border-slate-700 p-1" value={status} onChange={e=>setStatus(e.target.value)}>{['trialing','active','past_due','suspended','canceled'].map(v=><option key={v}>{v}</option>)}</select><div className="text-xs text-slate-500 mt-1">tenant: {tenant.status}</div></td><td className="p-2 text-right space-x-1"><button onClick={save} className="rounded bg-sky-700 px-2 py-1">Save</button>{tenant.status==='active'?<button onClick={()=>tenantStatus('suspended')} className="rounded bg-amber-800 px-2 py-1">Suspend</button>:<button onClick={()=>tenantStatus('active')} className="rounded bg-emerald-800 px-2 py-1">Activate</button>}</td></tr>
}
