import React from 'react';
import {Head, Link, router, useForm, usePage} from '@inertiajs/react';
import {ArrowLeft, CircleDollarSign, Globe2, MapPin, Radio, Smartphone, Trash2, UserRound, Wifi} from 'lucide-react';
import Layout from '../../components/Layout';
import {EmptyState, MetricCard, PageHeader, Surface} from '../../components/Ui';
import {useAccess} from '../../hooks/useAccess';

const input='w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none transition focus:border-[var(--jk-primary)] focus:ring-2 focus:ring-blue-100';

type Plan={id:number,name:string,code:string,price:number,download_kbps:number,upload_kbps:number};
type RouterRow={id:number,name:string,host:string,status:string};
type Nas={id:number,router_id?:number,shortname:string,nasname:string};
type Pool={id:number,name:string,start_ip:string,end_ip:string};
type OnlineSession={radacctid:number,acctsessionid:string,framedipaddress?:string,nasipaddress?:string,acctstarttime?:string,acctupdatetime?:string,acctsessiontime?:number,acctinputoctets?:number,acctoutputoctets?:number,callingstationid?:string};
type Service={id:number,service_number:string,service_type:string,pppoe_username:string,status:string,billing_day:number,due_day:number,static_ip?:string,installed_at?:string,last_radius_sync_at?:string,last_coa_at?:string,last_disconnect_at?:string,notes?:string,internet_plan_id:number,router_id?:number,network_nas_id?:number,ip_pool_id?:number,plan?:Plan,router?:RouterRow,nas?:Nas,ip_pool?:Pool,status_histories?:any[],accounting_sessions?:OnlineSession[]};
type Customer={id:number,customer_number:string,name:string,customer_type:string,identity_number?:string,email?:string,phone?:string,secondary_phone?:string,status:string,notes?:string,addresses:any[],contacts:any[],services:Service[],invoices?:any[],portal_account?:{id:number,email?:string,status:string,must_change_password:boolean,last_login_at?:string,portal_enabled_at?:string}};

export default function CustomerShow({customer,plans,routers,nas,pools,serviceStatuses}:{customer:Customer,plans:Plan[],routers:RouterRow[],nas:Nas[],pools:Pool[],serviceStatuses:string[]}){
  const {can}=useAccess();
  const canManage=can('customers.manage');
  const canBilling=can('billing.view');
  const canNetworkManage=can('network.manage');
  const page:any=usePage().props;
  const edit=useForm({name:customer.name,customer_type:customer.customer_type,identity_number:customer.identity_number||'',email:customer.email||'',phone:customer.phone||'',secondary_phone:customer.secondary_phone||'',status:customer.status,notes:customer.notes||''});
  const address=useForm({label:'Instalasi',address_line:'',village:'',district:'',city:'',province:'',postal_code:'',latitude:'',longitude:'',is_primary:customer.addresses.length===0});
  const contact=useForm({label:'Utama',type:'whatsapp',value:'',is_primary:customer.contacts.length===0});
  const service=useForm({internet_plan_id:plans[0]?.id||'',router_id:'',network_nas_id:'',ip_pool_id:'',pppoe_username:'',pppoe_password:'',status:'pending_installation',billing_day:1,due_day:10,static_ip:'',notes:'',status_reason:''});
  const portal=useForm({email:customer.portal_account?.email||customer.email||'',password:''});
  const activeServices=customer.services.filter(s=>s.status==='active').length;
  const onlineSessions=customer.services.reduce((n,s)=>n+(s.accounting_sessions?.length||0),0);

  return <Layout><Head title={`${customer.customer_number} - ${customer.name}`}/><div className="space-y-6">
    <PageHeader
      eyebrow="Customer 360"
      title={customer.name}
      description={`${customer.customer_number} · ${customer.customer_type==='business'?'Pelanggan usaha':'Pelanggan rumah'} · ${customer.phone||'Nomor HP belum diisi'}`}
      actions={<><Link href="/customers" className="jk-btn secondary"><ArrowLeft size={16}/> Kembali</Link>{canManage&&<button onClick={()=>confirm('Hapus pelanggan ini? Pelanggan dengan layanan tidak dapat dihapus.')&&router.delete(`/customers/${customer.id}`)} className="jk-btn secondary text-rose-600"><Trash2 size={16}/> Hapus</button>}</>}
    />

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <MetricCard icon={Wifi} label="Total Layanan" value={customer.services.length} hint={`${activeServices} layanan aktif`} tone="blue"/>
      <MetricCard icon={Radio} label="Online Session" value={onlineSessions} hint="Session RADIUS aktif" tone="emerald"/>
      <MetricCard icon={MapPin} label="Alamat" value={customer.addresses.length} hint="Alamat tersimpan" tone="cyan"/>
      <MetricCard icon={Smartphone} label="Kontak" value={customer.contacts.length} hint="Kontak tambahan" tone="violet"/>
    </section>

    <section className="grid gap-6 xl:grid-cols-3">
      <Surface title="Profil Pelanggan" subtitle={canManage?'Data dapat diperbarui sesuai hak akses Anda.':'Mode baca-saja. Role Anda tidak memiliki customers.manage.'} className="xl:col-span-2">
        {canManage?<form className="grid gap-4 md:grid-cols-2" onSubmit={e=>{e.preventDefault();edit.put(`/customers/${customer.id}`,{preserveScroll:true});}}>
          <Field label="Nama pelanggan"><input className={input} value={edit.data.name} onChange={e=>edit.setData('name',e.target.value)}/></Field>
          <Field label="Jenis pelanggan"><select className={input} value={edit.data.customer_type} onChange={e=>edit.setData('customer_type',e.target.value)}><option value="residential">Rumah / Residential</option><option value="business">Usaha / Business</option></select></Field>
          <Field label="NIK / identitas"><input className={input} value={edit.data.identity_number} onChange={e=>edit.setData('identity_number',e.target.value)}/></Field>
          <Field label="Email"><input className={input} type="email" value={edit.data.email} onChange={e=>edit.setData('email',e.target.value)}/></Field>
          <Field label="Nomor HP"><input className={input} value={edit.data.phone} onChange={e=>edit.setData('phone',e.target.value)}/></Field>
          <Field label="HP alternatif"><input className={input} value={edit.data.secondary_phone} onChange={e=>edit.setData('secondary_phone',e.target.value)}/></Field>
          <Field label="Status"><select className={input} value={edit.data.status} onChange={e=>edit.setData('status',e.target.value)}><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select></Field>
          <Field label="Catatan"><textarea className={input} value={edit.data.notes} onChange={e=>edit.setData('notes',e.target.value)} rows={3}/></Field>
          {Object.keys(edit.errors).length>0&&<div className="md:col-span-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-semibold text-rose-700">{Object.values(edit.errors).join(' · ')}</div>}
          <div className="md:col-span-2 flex justify-end"><button className="jk-btn primary" disabled={edit.processing}>{edit.processing?'Menyimpan...':'Simpan Profil'}</button></div>
        </form>:<div className="grid gap-3 sm:grid-cols-2"><Info label="Nama" value={customer.name}/><Info label="Jenis" value={customer.customer_type==='business'?'Usaha':'Rumah'}/><Info label="NIK / identitas" value={customer.identity_number||'-'}/><Info label="Email" value={customer.email||'-'}/><Info label="Nomor HP" value={customer.phone||'-'}/><Info label="HP alternatif" value={customer.secondary_phone||'-'}/><Info label="Status" value={customer.status}/><Info label="Catatan" value={customer.notes||'-'}/></div>}
      </Surface>

      <Surface title="Ringkasan Akun" subtitle="Informasi utama customer."><div className="space-y-3"><Info label="Nomor pelanggan" value={customer.customer_number}/><Info label="Status" value={<Status value={customer.status}/>}/><Info label="Layanan aktif" value={`${activeServices} / ${customer.services.length}`}/><Info label="Portal" value={customer.portal_account?.status||'Belum dibuat'}/><Info label="Alamat" value={customer.addresses.length}/><Info label="Kontak" value={customer.contacts.length}/></div></Surface>
    </section>

    <Surface title="Customer Portal" subtitle="Akun self-service pelanggan untuk melihat tagihan, profil, dan tiket.">
      <div className="grid gap-5 lg:grid-cols-3">
        <div className="lg:col-span-2">
          {customer.portal_account?<div className="grid gap-3 sm:grid-cols-2"><Info label="Status" value={customer.portal_account.status}/><Info label="Email login" value={customer.portal_account.email||'-'}/><Info label="Harus ganti password" value={customer.portal_account.must_change_password?'Ya':'Tidak'}/><Info label="Login terakhir" value={customer.portal_account.last_login_at?new Date(customer.portal_account.last_login_at).toLocaleString('id-ID'):'-'}/><div className="sm:col-span-2 rounded-xl bg-slate-50 p-3 text-xs text-slate-500"><Globe2 size={15} className="mb-1 inline text-[var(--jk-primary)]"/> URL portal: <span className="font-semibold text-[var(--jk-primary)]">/portal/{page.tenant?.slug||'tenant'}/login</span></div></div>:<EmptyState text="Portal pelanggan belum diaktifkan."/>}
          {page.flash?.generated_portal_password&&<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3"><div className="text-xs font-bold text-amber-700">Password sementara — tampil sekali</div><div className="mt-1 break-all font-mono font-bold text-amber-900">{page.flash.generated_portal_password}</div></div>}
        </div>
        {canManage&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();portal.post(`/customers/${customer.id}/portal-account`,{preserveScroll:true,onSuccess:()=>portal.reset('password')});}}><Field label="Email portal"><input className={input} type="email" value={portal.data.email} onChange={e=>portal.setData('email',e.target.value)}/></Field><Field label="Password"><input className={input} type="password" value={portal.data.password} onChange={e=>portal.setData('password',e.target.value)} placeholder="Kosong = generate otomatis"/></Field><button className="jk-btn primary w-full" disabled={portal.processing}>{customer.portal_account?'Aktifkan / Reset Akun':'Aktifkan Portal'}</button>{customer.portal_account&&<><button type="button" onClick={()=>router.post(`/customers/${customer.id}/portal-account/reset-password`,{}, {preserveScroll:true})} className="jk-btn secondary w-full">Generate Password Baru</button><button type="button" onClick={()=>router.put(`/customers/${customer.id}/portal-account/status`,{status:customer.portal_account?.status==='active'?'disabled':'active'},{preserveScroll:true})} className="jk-btn secondary w-full">{customer.portal_account.status==='active'?'Nonaktifkan Portal':'Aktifkan Portal'}</button></>}</form>}
      </div>
    </Surface>

    <section className="grid gap-6 xl:grid-cols-2">
      <Surface title="Alamat" subtitle="Alamat instalasi dan lokasi pelanggan.">
        {canManage&&<form className="mb-5 space-y-3" onSubmit={e=>{e.preventDefault();address.post(`/customers/${customer.id}/addresses`,{preserveScroll:true,onSuccess:()=>address.reset('address_line','village','district','city','province','postal_code','latitude','longitude')});}}><div className="grid gap-3 sm:grid-cols-2"><Field label="Label"><input className={input} value={address.data.label} onChange={e=>address.setData('label',e.target.value)}/></Field><label className="flex items-center gap-2 pt-7 text-sm font-semibold text-slate-600"><input type="checkbox" checked={address.data.is_primary} onChange={e=>address.setData('is_primary',e.target.checked)}/> Alamat utama</label></div><Field label="Alamat lengkap"><textarea className={input} value={address.data.address_line} onChange={e=>address.setData('address_line',e.target.value)} rows={3}/></Field><div className="grid gap-3 sm:grid-cols-2"><input className={input} value={address.data.village} onChange={e=>address.setData('village',e.target.value)} placeholder="Kelurahan"/><input className={input} value={address.data.district} onChange={e=>address.setData('district',e.target.value)} placeholder="Kecamatan"/><input className={input} value={address.data.city} onChange={e=>address.setData('city',e.target.value)} placeholder="Kota/Kabupaten"/><input className={input} value={address.data.province} onChange={e=>address.setData('province',e.target.value)} placeholder="Provinsi"/></div><div className="grid gap-3 sm:grid-cols-3"><input className={input} value={address.data.postal_code} onChange={e=>address.setData('postal_code',e.target.value)} placeholder="Kode pos"/><input className={input} value={address.data.latitude} onChange={e=>address.setData('latitude',e.target.value)} placeholder="Latitude"/><input className={input} value={address.data.longitude} onChange={e=>address.setData('longitude',e.target.value)} placeholder="Longitude"/></div><button className="jk-btn primary" disabled={address.processing}>Tambah Alamat</button></form>}
        <div className="space-y-2">{customer.addresses.map(a=><div key={a.id} className="flex justify-between gap-3 rounded-xl border border-slate-200 p-3"><div><div className="font-bold text-slate-800">{a.label} {a.is_primary&&<span className="ml-1 rounded-full bg-blue-50 px-2 py-0.5 text-[10px] font-bold text-blue-700">UTAMA</span>}</div><div className="mt-1 text-xs text-slate-600">{a.address_line}</div><div className="mt-1 text-xs text-slate-400">{[a.village,a.district,a.city,a.province,a.postal_code].filter(Boolean).join(', ')}</div></div>{canManage&&<button onClick={()=>confirm('Hapus alamat?')&&router.delete(`/customers/${customer.id}/addresses/${a.id}`,{preserveScroll:true})} className="h-fit text-xs font-bold text-rose-600">Hapus</button>}</div>)}{customer.addresses.length===0&&<EmptyState text="Belum ada alamat pelanggan."/>}</div>
      </Surface>

      <Surface title="Kontak Tambahan" subtitle="WhatsApp, telepon, email, atau kontak lain.">
        {canManage&&<form className="mb-5 grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();contact.post(`/customers/${customer.id}/contacts`,{preserveScroll:true,onSuccess:()=>contact.reset('value')});}}><Field label="Label"><input className={input} value={contact.data.label} onChange={e=>contact.setData('label',e.target.value)}/></Field><Field label="Jenis"><select className={input} value={contact.data.type} onChange={e=>contact.setData('type',e.target.value)}><option value="whatsapp">WhatsApp</option><option value="phone">Phone</option><option value="email">Email</option><option value="other">Lainnya</option></select></Field><div className="sm:col-span-2"><Field label="Nomor / email"><input className={input} value={contact.data.value} onChange={e=>contact.setData('value',e.target.value)}/></Field></div><label className="flex items-center gap-2 text-sm font-semibold text-slate-600"><input type="checkbox" checked={contact.data.is_primary} onChange={e=>contact.setData('is_primary',e.target.checked)}/> Kontak utama</label><button className="jk-btn primary" disabled={contact.processing}>Tambah Kontak</button></form>}
        <div className="space-y-2">{customer.contacts.map(c=><div key={c.id} className="flex justify-between gap-3 rounded-xl border border-slate-200 p-3"><div><div className="font-bold text-slate-800">{c.label} {c.is_primary&&<span className="ml-1 rounded-full bg-blue-50 px-2 py-0.5 text-[10px] font-bold text-blue-700">UTAMA</span>}</div><div className="mt-1 text-xs text-slate-500">{c.type} · {c.value}</div></div>{canManage&&<button onClick={()=>confirm('Hapus kontak?')&&router.delete(`/customers/${customer.id}/contacts/${c.id}`,{preserveScroll:true})} className="text-xs font-bold text-rose-600">Hapus</button>}</div>)}{customer.contacts.length===0&&<EmptyState text="Belum ada kontak tambahan."/>}</div>
      </Surface>
    </section>

    {canManage&&<Surface title="Tambah Layanan Internet / PPPoE" subtitle="Buat layanan baru dan sinkronkan data autentikasi ke RADIUS."><form className="grid gap-3 md:grid-cols-2 xl:grid-cols-4" onSubmit={e=>{e.preventDefault();service.post(`/customers/${customer.id}/services`,{preserveScroll:true,onSuccess:()=>service.reset('pppoe_username','pppoe_password','static_ip','notes')});}}><select className={input} value={service.data.internet_plan_id} onChange={e=>service.setData('internet_plan_id',Number(e.target.value))}><option value="">Pilih paket *</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name} · Rp {Number(p.price).toLocaleString('id-ID')}</option>)}</select><select className={input} value={service.data.router_id} onChange={e=>service.setData('router_id',e.target.value)}><option value="">Router belum ditentukan</option>{routers.map(r=><option key={r.id} value={r.id}>{r.name} ({r.host})</option>)}</select><select className={input} value={service.data.network_nas_id} onChange={e=>service.setData('network_nas_id',e.target.value)}><option value="">NAS belum ditentukan</option>{nas.map(n=><option key={n.id} value={n.id}>{n.shortname} · {n.nasname}</option>)}</select><select className={input} value={service.data.ip_pool_id} onChange={e=>service.setData('ip_pool_id',e.target.value)}><option value="">Tanpa IP Pool</option>{pools.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input className={input} value={service.data.pppoe_username} onChange={e=>service.setData('pppoe_username',e.target.value)} placeholder="PPPoE username *"/><input className={input} type="password" value={service.data.pppoe_password} onChange={e=>service.setData('pppoe_password',e.target.value)} placeholder="PPPoE password *"/><select className={input} value={service.data.status} onChange={e=>service.setData('status',e.target.value)}>{serviceStatuses.map(s=><option key={s} value={s}>{s}</option>)}</select><input className={input} value={service.data.static_ip} onChange={e=>service.setData('static_ip',e.target.value)} placeholder="Static IP (opsional)"/><input className={input} type="number" min={1} max={28} value={service.data.billing_day} onChange={e=>service.setData('billing_day',Number(e.target.value))} placeholder="Billing day"/><input className={input} type="number" min={1} max={28} value={service.data.due_day} onChange={e=>service.setData('due_day',Number(e.target.value))} placeholder="Due day"/><textarea className={`${input} xl:col-span-2`} value={service.data.notes} onChange={e=>service.setData('notes',e.target.value)} placeholder="Catatan layanan" rows={2}/>{Object.keys(service.errors).length>0&&<div className="xl:col-span-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-semibold text-rose-700">{Object.values(service.errors).join(' · ')}</div>}<button className="jk-btn primary xl:col-span-4" disabled={service.processing}>Buat Layanan & Sync RADIUS</button></form></Surface>}

    {canBilling&&customer.invoices&&customer.invoices.length>0&&<Surface title="Invoice Terbaru" subtitle="12 invoice terakhir pelanggan."><div className="space-y-2">{customer.invoices.map((inv:any)=><Link key={inv.id} href={`/billing/invoices/${inv.id}`} className="flex flex-col justify-between gap-2 rounded-xl border border-slate-200 p-3 transition hover:border-blue-300 hover:bg-blue-50/30 md:flex-row md:items-center"><div><div className="font-bold text-[var(--jk-primary)]">{inv.invoice_number}</div><div className="mt-1 text-xs text-slate-500">{inv.service?.service_number||'-'} · {inv.service?.pppoe_username||'-'} · jatuh tempo {new Date(inv.due_at+'T00:00:00').toLocaleDateString('id-ID')}</div></div><div className="text-right"><div className="font-black text-slate-900">Rp{Number(inv.balance_due||0).toLocaleString('id-ID')}</div><div className="text-[10px] font-bold uppercase text-slate-400">{inv.status}</div></div></Link>)}</div><Link href="/billing" className="jk-btn secondary mt-4"><CircleDollarSign size={16}/> Buka Billing</Link></Surface>}

    <section className="space-y-4"><div><div className="jk-eyebrow">Internet Services</div><h2 className="mt-1 text-xl font-black text-slate-950">Layanan Pelanggan</h2></div>{customer.services.map(s=><ServiceCard key={s.id} customerId={customer.id} service={s} plans={plans} routers={routers} nas={nas} pools={pools} statuses={serviceStatuses} canManage={canManage} canNetworkManage={canNetworkManage}/>)}{customer.services.length===0&&<Surface><EmptyState text="Belum ada layanan internet."/></Surface>}</section>
  </div></Layout>;
}

function ServiceCard({customerId,service,plans,routers,nas,pools,statuses,canManage,canNetworkManage}:{customerId:number,service:Service,plans:Plan[],routers:RouterRow[],nas:Nas[],pools:Pool[],statuses:string[],canManage:boolean,canNetworkManage:boolean}){
  const form=useForm({internet_plan_id:service.internet_plan_id,router_id:service.router_id||'',network_nas_id:service.network_nas_id||'',ip_pool_id:service.ip_pool_id||'',pppoe_username:service.pppoe_username,pppoe_password:'',status:service.status,billing_day:service.billing_day,due_day:service.due_day,static_ip:service.static_ip||'',notes:service.notes||'',status_reason:''});
  return <Surface><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-black text-slate-900">{service.service_number}</h3><Status value={service.status}/><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase text-slate-500">{service.service_type}</span></div><div className="mt-1 text-sm font-bold text-[var(--jk-primary)]">{service.pppoe_username}</div><div className="mt-2 text-xs leading-5 text-slate-500">{service.plan?.name||'-'} · {service.router?.name||'Router -'} · {service.nas?.shortname||'NAS -'} · Pool {service.ip_pool?.name||'-'}</div><div className="text-xs text-slate-400">Last RADIUS sync: {service.last_radius_sync_at?new Date(service.last_radius_sync_at).toLocaleString('id-ID'):'belum'}</div></div>{canManage&&<div className="flex flex-wrap gap-2"><button onClick={()=>router.post(`/customers/${customerId}/services/${service.id}/radius-sync`,{}, {preserveScroll:true})} className="jk-btn secondary text-xs">Sync RADIUS</button><button onClick={()=>confirm('Terminasi dan hapus layanan ini?')&&router.delete(`/customers/${customerId}/services/${service.id}`,{preserveScroll:true})} className="jk-btn secondary text-xs text-rose-600">Terminasi</button></div>}</div>
    {service.accounting_sessions&&service.accounting_sessions.length>0&&<div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50/60 p-3"><div className="mb-2 text-xs font-black text-emerald-700">ONLINE SESSION ({service.accounting_sessions.length})</div><div className="space-y-2">{service.accounting_sessions.map(a=><div key={a.radacctid} className="flex flex-col justify-between gap-2 rounded-xl border border-emerald-100 bg-white p-3 lg:flex-row lg:items-center"><div className="text-xs text-slate-600"><span className="font-bold text-[var(--jk-primary)]">{a.framedipaddress||'-'}</span> · NAS {a.nasipaddress||'-'} · MAC {a.callingstationid||'-'}<div className="mt-1 text-slate-400">Session {a.acctsessionid} · start {a.acctstarttime?new Date(a.acctstarttime).toLocaleString('id-ID'):'-'}</div></div>{canNetworkManage&&<div className="flex gap-2"><button onClick={()=>router.post(`/network/sessions/${a.radacctid}/coa`,{}, {preserveScroll:true})} className="jk-btn secondary !px-3 !py-1.5 text-[11px]">CoA Paket</button><button onClick={()=>confirm('Disconnect session ini?')&&router.post(`/network/sessions/${a.radacctid}/disconnect`,{}, {preserveScroll:true})} className="jk-btn secondary !px-3 !py-1.5 text-[11px] text-rose-600">Disconnect</button></div>}</div>)}</div></div>}
    {canManage?<form className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4" onSubmit={e=>{e.preventDefault();form.put(`/customers/${customerId}/services/${service.id}`,{preserveScroll:true,onSuccess:()=>form.reset('pppoe_password','status_reason')});}}><select className={input} value={form.data.internet_plan_id} onChange={e=>form.setData('internet_plan_id',Number(e.target.value))}>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select className={input} value={form.data.router_id} onChange={e=>form.setData('router_id',e.target.value)}><option value="">Router -</option>{routers.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><select className={input} value={form.data.network_nas_id} onChange={e=>form.setData('network_nas_id',e.target.value)}><option value="">NAS -</option>{nas.map(n=><option key={n.id} value={n.id}>{n.shortname}</option>)}</select><select className={input} value={form.data.ip_pool_id} onChange={e=>form.setData('ip_pool_id',e.target.value)}><option value="">Pool -</option>{pools.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input className={input} value={form.data.pppoe_username} onChange={e=>form.setData('pppoe_username',e.target.value)} placeholder="PPPoE username"/><input className={input} type="password" value={form.data.pppoe_password} onChange={e=>form.setData('pppoe_password',e.target.value)} placeholder="Password baru (kosong = tetap)"/><select className={input} value={form.data.status} onChange={e=>form.setData('status',e.target.value)}>{statuses.map(s=><option key={s} value={s}>{s}</option>)}</select><input className={input} value={form.data.static_ip} onChange={e=>form.setData('static_ip',e.target.value)} placeholder="Static IP"/><input className={input} type="number" min={1} max={28} value={form.data.billing_day} onChange={e=>form.setData('billing_day',Number(e.target.value))}/><input className={input} type="number" min={1} max={28} value={form.data.due_day} onChange={e=>form.setData('due_day',Number(e.target.value))}/><input className={`${input} xl:col-span-2`} value={form.data.status_reason} onChange={e=>form.setData('status_reason',e.target.value)} placeholder="Alasan perubahan status (opsional)"/><textarea className={`${input} xl:col-span-3`} value={form.data.notes} onChange={e=>form.setData('notes',e.target.value)} placeholder="Catatan" rows={2}/><button className="jk-btn primary" disabled={form.processing}>Simpan & Sync</button></form>:<div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Info label="Paket" value={service.plan?.name||'-'}/><Info label="Router" value={service.router?.name||'-'}/><Info label="NAS" value={service.nas?.shortname||'-'}/><Info label="IP Pool" value={service.ip_pool?.name||'-'}/><Info label="Static IP" value={service.static_ip||'-'}/><Info label="Billing day" value={service.billing_day}/><Info label="Due day" value={service.due_day}/><Info label="Catatan" value={service.notes||'-'}/></div>}
    {service.status_histories&&service.status_histories.length>0&&<details className="mt-4 rounded-xl border border-slate-200 p-3"><summary className="cursor-pointer text-xs font-bold text-slate-600">Riwayat status ({service.status_histories.length})</summary><div className="mt-3 space-y-2">{service.status_histories.map(h=><div key={h.id} className="border-l-2 border-slate-200 pl-3 text-xs text-slate-500"><span className="font-bold text-slate-700">{h.from_status||'NEW'} → {h.to_status}</span> · {h.reason||'-'} · {h.actor?.name||'system'} · {new Date(h.created_at).toLocaleString('id-ID')}</div>)}</div></details>}
  </Surface>;
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1 block text-xs font-bold text-slate-700">{label}</span>{children}</label>}
function Info({label,value}:{label:string;value:React.ReactNode}){return <div className="rounded-xl bg-slate-50 p-3"><div className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}</div><div className="mt-1 break-words text-sm font-semibold text-slate-800">{value}</div></div>}
function Status({value}:{value:string}){const map:Record<string,string>={active:'bg-emerald-50 text-emerald-700 ring-emerald-200',suspended:'bg-amber-50 text-amber-700 ring-amber-200',terminated:'bg-rose-50 text-rose-700 ring-rose-200',pending_installation:'bg-blue-50 text-blue-700 ring-blue-200',inactive:'bg-slate-100 text-slate-600 ring-slate-200',draft:'bg-slate-100 text-slate-600 ring-slate-200'};return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold uppercase ring-1 ${map[value]||'bg-slate-100 text-slate-600 ring-slate-200'}`}>{value.replaceAll('_',' ')}</span>}
