<?php
namespace App\Http\Controllers\Inventory;
use App\Http\Controllers\Controller;
use App\Models\CustomerService;
use App\Models\InventoryItem;
use App\Models\InventoryLocation;
use App\Models\InventorySku;
use App\Services\InventoryLedgerService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
class InventoryTransactionController extends Controller {
    private function write(Request $r):object { $a=$r->attributes->get('inventory_account'); abort_unless($a?->canWrite(),403); return $a; }
    public function receive(Request $r,InventoryLedgerService $ledger):RedirectResponse { $a=$this->write($r); abort_if($a->role==='technician',403); $d=$r->validate(['to_location_id'=>'required|integer','inventory_sku_id'=>'required|integer','quantity'=>'required|numeric|min:0.001','unit_cost'=>'nullable|numeric|min:0','supplier_id'=>'nullable|integer','purchase_order_id'=>'nullable|integer','notes'=>'nullable|string|max:2000','serials'=>'nullable|string|max:10000']); $loc=InventoryLocation::findOrFail($d['to_location_id']); $sku=InventorySku::findOrFail($d['inventory_sku_id']); $assets=[]; if($sku->serialized){ foreach(preg_split('/\r\n|\r|\n/',trim((string)($d['serials']??''))) as $line){ if(trim($line)==='')continue; [$sn,$mac,$barcode]=array_pad(array_map('trim',explode(',',$line,3)),3,''); $assets[]=['serial_number'=>$sn,'mac_address'=>$mac,'barcode'=>$barcode]; } } $ledger->receive($loc,$sku,(float)$d['quantity'],(float)($d['unit_cost']??0),$assets,$d['supplier_id']??null,$d['purchase_order_id']??null,$a->id,null,$d['notes']??null); return back()->with('success','Penerimaan stok berhasil diposting.'); }
    public function transfer(Request $r,InventoryLedgerService $ledger):RedirectResponse { $a=$this->write($r); $d=$r->validate(['from_location_id'=>'required|integer','to_location_id'=>'required|integer|different:from_location_id','inventory_sku_id'=>'required|integer','quantity'=>'required|numeric|min:0.001','asset_ids'=>'nullable|array','asset_ids.*'=>'integer','notes'=>'nullable|string|max:2000']); $from=InventoryLocation::findOrFail($d['from_location_id']); $to=InventoryLocation::findOrFail($d['to_location_id']); if($a->role==='technician'){ abort_unless((int)$a->inventory_location_id===(int)$from->id,403); abort_if($to->location_type==='technician' && (int)$to->id!==(int)$from->id,403,'Teknisi tidak dapat memindahkan stok langsung ke teknisi lain.'); } $sku=InventorySku::findOrFail($d['inventory_sku_id']); $ledger->transfer($from,$to,$sku,(float)$d['quantity'],$d['asset_ids']??[],$a->id,null,$d['notes']??null,$to->location_type==='technician'?'issue':'transfer'); return back()->with('success','Transfer inventory berhasil diposting.'); }
    public function install(Request $r,InventoryLedgerService $ledger):RedirectResponse { $a=$this->write($r); $d=$r->validate(['asset_id'=>'required|integer','customer_service_id'=>'required|integer','notes'=>'nullable|string|max:2000']); $asset=InventoryItem::findOrFail($d['asset_id']); if($a->role==='technician') abort_unless((int)$a->inventory_location_id===(int)$asset->current_location_id,403); $service=CustomerService::findOrFail($d['customer_service_id']); $ledger->installAsset($asset,$service,$a->id,null,$d['notes']??null); return back()->with('success','Asset dipasang ke pelanggan dan stok diperbarui.'); }
    public function retrieve(Request $r,InventoryLedgerService $ledger):RedirectResponse { $a=$this->write($r); $d=$r->validate(['asset_id'=>'required|integer','to_location_id'=>'required|integer','condition'=>'required|in:good,repair,damaged','notes'=>'nullable|string|max:2000']); $asset=InventoryItem::findOrFail($d['asset_id']); $to=InventoryLocation::findOrFail($d['to_location_id']); if($a->role==='technician') abort_unless((int)$a->inventory_location_id===(int)$to->id,403); $ledger->retrieveAsset($asset,$to,$a->id,null,$d['condition'],$d['notes']??null); return back()->with('success','Asset pelanggan berhasil diretrieve.'); }
    public function opname(Request $r,InventoryLedgerService $ledger):RedirectResponse { $a=$this->write($r); abort_if($a->role==='technician',403); $d=$r->validate(['inventory_location_id'=>'required|integer','inventory_sku_id'=>'required|integer','counted_quantity'=>'required|numeric|min:0','notes'=>'nullable|string|max:2000']); $ledger->stockOpname(InventoryLocation::findOrFail($d['inventory_location_id']),InventorySku::findOrFail($d['inventory_sku_id']),(float)$d['counted_quantity'],$a->id,$d['notes']??null); return back()->with('success','Stock opname diposting dan variance dicatat.'); }
}
