import React,{useState} from 'react';
import PartnerLayout from '../../components/PartnerLayout';
import {router,useForm,usePage} from '@inertiajs/react';
import {Search,UserPlus} from 'lucide-react';
const money=(n:any)=>'Rp'+new Intl.NumberFormat('id-ID').format(Number(n||0));
const input='mt-1.5 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100';
function Field({label,help,error,children}:any){return <label className="block text-sm font-semibold text-slate-700">{label}{children}{help&&<span className="mt-1 block text-xs font-normal text-slate-400">{help}</span>}{error&&<span className="mt-1 block text-xs font-normal text-rose-600">{error}</span>}</label>}
export default function Customers({customers,filters,plans}:any){
 const p:any=usePage().props; const slug=p.tenant.slug; const role=p.partner?.account?.role||'sales'; const canCreate=['owner','admin','sales'].includes(role); const [q,setQ]=useState(filters.q||'');
 const f=useForm({name:'',email:'',phone:'',address_line:'',city:'',notes:'',internet_plan_id:''});
 const submit=(e:React.FormEvent)=>{e.preventDefault();f.post(`/mitra/${slug}/customers`,{preserveScroll:true,onSuccess:()=>f.reset()})};
 return <PartnerLayout tenantSlug={slug}><div className="mb-6"><h1 className="text-2xl font-black">Pelanggan Mitra</h1><p className="mt-1 text-sm text-slate-500">Daftarkan calon pelanggan dan pantau pelanggan yang berada di bawah mitra ini.</p></div><div className={`grid gap-5 ${canCreate?'xl:grid-cols-[390px_1fr]':''}`}>
 {canCreate&&<form onSubmit={submit} className="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><div className="rounded-lg bg-blue-50 p-2 text-[#0f6cbd]"><UserPlus size={18}/></div><div><h2 className="font-bold">Tambah Pelanggan</h2><p className="text-xs text-slate-500">Request instalasi otomatis dibuat jika paket dipilih.</p></div></div><div className="mt-5 space-y-4"><Field label="Nama pelanggan" error={f.errors.name}><input className={input} value={f.data.name} onChange={e=>f.setData('name',e.target.value)} placeholder="Contoh: Budi Santoso"/></Field><div className="grid grid-cols-2 gap-3"><Field label="Nomor WhatsApp / HP" error={f.errors.phone}><input className={input} value={f.data.phone} onChange={e=>f.setData('phone',e.target.value)} placeholder="08..."/></Field><Field label="Email (opsional)" error={f.errors.email}><input type="email" className={input} value={f.data.email} onChange={e=>f.setData('email',e.target.value)} placeholder="nama@email.com"/></Field></div><Field label="Alamat pemasangan" error={f.errors.address_line}><textarea rows={3} className={input} value={f.data.address_line} onChange={e=>f.setData('address_line',e.target.value)} placeholder="Jalan, RT/RW, desa/kelurahan"/></Field><Field label="Kota / Kecamatan"><input className={input} value={f.data.city} onChange={e=>f.setData('city',e.target.value)} placeholder="Kaliwungu"/></Field><Field label="Paket internet" help="Boleh dikosongkan jika paket akan ditentukan oleh admin ISP."><select className={input} value={f.data.internet_plan_id} onChange={e=>f.setData('internet_plan_id',e.target.value)}><option value="">Belum pilih paket</option>{plans.map((x:any)=><option key={x.id} value={x.id}>{x.name} · {money(x.price)}</option>)}</select></Field><Field label="Catatan (opsional)"><textarea rows={2} className={input} value={f.data.notes} onChange={e=>f.setData('notes',e.target.value)} placeholder="Patokan rumah, jadwal instalasi, dll."/></Field><button disabled={f.processing} className="w-full rounded-xl bg-[#0f6cbd] px-4 py-3 font-bold text-white disabled:opacity-50">Simpan & Buat Request</button></div></form>}
 <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="font-bold">Daftar Pelanggan</h2><p className="text-xs text-slate-500">{customers.total||customers.data.length} pelanggan terdaftar.</p></div><form onSubmit={e=>{e.preventDefault();router.get(`/mitra/${slug}/customers`,{q},{preserveState:true,replace:true})}} className="flex min-w-0 gap-2"><div className="relative min-w-0 flex-1 md:w-72"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full rounded-xl border border-slate-300 py-2.5 pl-9 pr-3 text-sm" placeholder="Nama, nomor pelanggan, HP"/></div><button className="rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm font-semibold">Cari</button></form></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead><tr className="border-y border-slate-100 bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-400"><th className="px-3 py-3">No. Pelanggan</th><th>Nama</th><th>Kontak</th><th>Status</th><th className="text-right pr-3">Layanan</th></tr></thead><tbody>{customers.data.map((c:any)=><tr key={c.id} className="border-b border-slate-100"><td className="px-3 py-3 font-mono text-xs text-[#0f6cbd]">{c.customer_number}</td><td className="font-semibold">{c.name}</td><td className="text-slate-500">{c.phone||'-'}</td><td><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold uppercase text-emerald-700">{c.status}</span></td><td className="pr-3 text-right">{c.services_count}</td></tr>)}</tbody></table>{!customers.data.length&&<div className="py-12 text-center text-sm text-slate-400">Pelanggan tidak ditemukan.</div>}</div></section></div></PartnerLayout>;
}
