import React from 'react';
import {Head, router, useForm} from '@inertiajs/react';
import Layout from '../../components/Layout';
import {PageHeader} from '../../components/Ui';
import {useAccess} from '../../hooks/useAccess';

const input='w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100';
const select=input;

export default function FieldOps({stats,tickets,workOrders,installations,technicians,inventory,nodes,mapPoints,customers,services}:{stats:any,tickets:any[],workOrders:any[],installations:any[],technicians:any[],inventory:any[],nodes:any[],mapPoints:any[],customers:any[],services:any[]}){
 const tech=useForm({name:'',phone:'',email:'',skills:'fiber, pppoe',notes:''});
 const ticket=useForm({customer_id:'',customer_service_id:'',assigned_technician_id:'',category:'technical',priority:'normal',subject:'',description:''});
 const wo=useForm({customer_id:'',customer_service_id:'',support_ticket_id:'',technician_id:'',type:'repair',priority:'normal',scheduled_at:'',address:'',latitude:'',longitude:'',instructions:''});
 const inv=useForm({category:'ont',brand:'',model:'',serial_number:'',mac_address:'',purchase_date:'',warranty_until:'',notes:''});
 const node=useForm({name:'',node_type:'odp',parent_node_id:'',address:'',latitude:'',longitude:'',capacity_ports:'8',notes:''});
 const install=useForm({customer_service_id:'',technician_id:'',scheduled_at:'',installation_notes:''});
 const mapping=useForm({customer_service_id:'',network_node_id:'',port_number:'',cable_length_m:'',notes:''});
 const {can}=useAccess();
 const canManage=can('field_ops.manage');
 return <Layout><Head title="ISP Operations"/><div className="space-y-6">
  <PageHeader eyebrow="Operasional ISP" title="Teknisi, Ticket & Work Order" description="Kelola gangguan, penugasan teknisi, instalasi, inventory lapangan, ODP/ODC dan GIS-lite dari satu pusat operasi."/>
  <section className="grid grid-cols-2 gap-3 xl:grid-cols-6">{Object.entries({Tickets:stats.open_tickets,'Work Orders':stats.pending_work_orders,Installations:stats.pending_installations,Technicians:stats.active_technicians,Inventory:stats.available_inventory,'Network Nodes':stats.network_nodes}).map(([k,v])=><Metric key={k} label={k} value={v}/>)}</section>

  {canManage&&<section className="grid gap-5 xl:grid-cols-3">
   <Card title="Tambah Teknisi"><form onSubmit={e=>{e.preventDefault();tech.post('/field-operations/technicians',{preserveScroll:true,onSuccess:()=>tech.reset()})}} className="space-y-2"><input className={input} placeholder="Nama teknisi" value={tech.data.name} onChange={e=>tech.setData('name',e.target.value)}/><input className={input} placeholder="Telepon" value={tech.data.phone} onChange={e=>tech.setData('phone',e.target.value)}/><input className={input} placeholder="Email" value={tech.data.email} onChange={e=>tech.setData('email',e.target.value)}/><input className={input} placeholder="Skills, dipisah koma" value={tech.data.skills} onChange={e=>tech.setData('skills',e.target.value)}/><button className="rounded-lg bg-sky-600 px-4 py-2 text-sm font-semibold">Simpan Teknisi</button></form></Card>
   <Card title="Tambah Inventory"><form onSubmit={e=>{e.preventDefault();inv.post('/field-operations/inventory',{preserveScroll:true,onSuccess:()=>inv.reset()})}} className="grid grid-cols-2 gap-2"><input className={input} placeholder="Kategori (ONT/router)" value={inv.data.category} onChange={e=>inv.setData('category',e.target.value)}/><input className={input} placeholder="Brand" value={inv.data.brand} onChange={e=>inv.setData('brand',e.target.value)}/><input className={input} placeholder="Model" value={inv.data.model} onChange={e=>inv.setData('model',e.target.value)}/><input className={input} placeholder="Serial number" value={inv.data.serial_number} onChange={e=>inv.setData('serial_number',e.target.value)}/><input className={input} placeholder="MAC address" value={inv.data.mac_address} onChange={e=>inv.setData('mac_address',e.target.value)}/><button className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold">Tambah Asset</button></form></Card>
   <Card title="Tambah ODP/ODC"><form onSubmit={e=>{e.preventDefault();node.post('/field-operations/network-nodes',{preserveScroll:true,onSuccess:()=>node.reset()})}} className="grid grid-cols-2 gap-2"><input className={`${input} col-span-2`} placeholder="Nama node" value={node.data.name} onChange={e=>node.setData('name',e.target.value)}/><select className={select} value={node.data.node_type} onChange={e=>node.setData('node_type',e.target.value)}><option value="pop">POP</option><option value="olt">OLT</option><option value="odc">ODC</option><option value="odp">ODP</option><option value="splitter">Splitter</option></select><input className={input} type="number" placeholder="Kapasitas port" value={node.data.capacity_ports} onChange={e=>node.setData('capacity_ports',e.target.value)}/><input className={input} placeholder="Latitude" value={node.data.latitude} onChange={e=>node.setData('latitude',e.target.value)}/><input className={input} placeholder="Longitude" value={node.data.longitude} onChange={e=>node.setData('longitude',e.target.value)}/><button className="col-span-2 rounded-lg bg-violet-700 px-4 py-2 text-sm font-semibold">Tambah Node</button></form></Card>
  </section>}

  {canManage&&<section className="grid gap-5 xl:grid-cols-2">
   <Card title="Buat Ticket"><form onSubmit={e=>{e.preventDefault();ticket.post('/field-operations/tickets',{preserveScroll:true,onSuccess:()=>ticket.reset()})}} className="space-y-2"><select className={select} value={ticket.data.customer_id} onChange={e=>ticket.setData('customer_id',e.target.value)}><option value="">Pilih pelanggan</option>{customers.map(c=><option key={c.id} value={c.id}>{c.customer_number} · {c.name}</option>)}</select><div className="grid grid-cols-2 gap-2"><select className={select} value={ticket.data.category} onChange={e=>ticket.setData('category',e.target.value)}><option>technical</option><option>billing</option><option>installation</option><option>complaint</option><option>other</option></select><select className={select} value={ticket.data.priority} onChange={e=>ticket.setData('priority',e.target.value)}><option>low</option><option>normal</option><option>high</option><option>urgent</option></select></div><select className={select} value={ticket.data.assigned_technician_id} onChange={e=>ticket.setData('assigned_technician_id',e.target.value)}><option value="">Belum assign teknisi</option>{technicians.map(t=><option key={t.id} value={t.id}>{t.code} · {t.name}</option>)}</select><input className={input} placeholder="Subjek" value={ticket.data.subject} onChange={e=>ticket.setData('subject',e.target.value)}/><textarea className={input} placeholder="Deskripsi" value={ticket.data.description} onChange={e=>ticket.setData('description',e.target.value)}/><button className="rounded-lg bg-sky-600 px-4 py-2 text-sm font-semibold">Buat Ticket</button></form></Card>
   <Card title="Buat Work Order"><form onSubmit={e=>{e.preventDefault();wo.post('/field-operations/work-orders',{preserveScroll:true,onSuccess:()=>wo.reset()})}} className="space-y-2"><select className={select} value={wo.data.customer_id} onChange={e=>wo.setData('customer_id',e.target.value)}><option value="">Pilih pelanggan</option>{customers.map(c=><option key={c.id} value={c.id}>{c.customer_number} · {c.name}</option>)}</select><div className="grid grid-cols-2 gap-2"><select className={select} value={wo.data.type} onChange={e=>wo.setData('type',e.target.value)}><option>repair</option><option>installation</option><option>maintenance</option><option>survey</option><option>relocation</option><option>pickup</option></select><select className={select} value={wo.data.technician_id} onChange={e=>wo.setData('technician_id',e.target.value)}><option value="">Pilih teknisi</option>{technicians.map(t=><option key={t.id} value={t.id}>{t.code} · {t.name}</option>)}</select></div><input className={input} type="datetime-local" value={wo.data.scheduled_at} onChange={e=>wo.setData('scheduled_at',e.target.value)}/><textarea className={input} placeholder="Instruksi lapangan" value={wo.data.instructions} onChange={e=>wo.setData('instructions',e.target.value)}/><button className="rounded-lg bg-amber-700 px-4 py-2 text-sm font-semibold">Buat Work Order</button></form></Card>
  </section>}

  {canManage&&<section className="grid gap-5 xl:grid-cols-2">
   <Card title="Jadwalkan Instalasi"><form onSubmit={e=>{e.preventDefault();install.post('/field-operations/installations',{preserveScroll:true,onSuccess:()=>install.reset()})}} className="space-y-2"><select className={select} value={install.data.customer_service_id} onChange={e=>install.setData('customer_service_id',e.target.value)}><option value="">Pilih service</option>{services.map(s=><option key={s.id} value={s.id}>{s.service_number} · {s.customer?.name} · {s.pppoe_username}</option>)}</select><select className={select} value={install.data.technician_id} onChange={e=>install.setData('technician_id',e.target.value)}><option value="">Pilih teknisi</option>{technicians.map(t=><option key={t.id} value={t.id}>{t.code} · {t.name}</option>)}</select><input type="datetime-local" className={input} value={install.data.scheduled_at} onChange={e=>install.setData('scheduled_at',e.target.value)}/><textarea className={input} placeholder="Catatan instalasi" value={install.data.installation_notes} onChange={e=>install.setData('installation_notes',e.target.value)}/><button className="rounded-lg bg-indigo-700 px-4 py-2 text-sm font-semibold">Buat Job Instalasi</button></form></Card>
   <Card title="Mapping Service ke ODP/ODC"><form onSubmit={e=>{e.preventDefault();mapping.post('/field-operations/network-assignments',{preserveScroll:true,onSuccess:()=>mapping.reset()})}} className="space-y-2"><select className={select} value={mapping.data.customer_service_id} onChange={e=>mapping.setData('customer_service_id',e.target.value)}><option value="">Pilih service</option>{services.map(s=><option key={s.id} value={s.id}>{s.service_number} · {s.customer?.name}</option>)}</select><select className={select} value={mapping.data.network_node_id} onChange={e=>mapping.setData('network_node_id',e.target.value)}><option value="">Pilih node</option>{nodes.map(n=><option key={n.id} value={n.id}>{n.code} · {n.name}</option>)}</select><div className="grid grid-cols-2 gap-2"><input className={input} placeholder="Port (P1)" value={mapping.data.port_number} onChange={e=>mapping.setData('port_number',e.target.value)}/><input className={input} type="number" placeholder="Kabel (meter)" value={mapping.data.cable_length_m} onChange={e=>mapping.setData('cable_length_m',e.target.value)}/></div><button className="rounded-lg bg-violet-700 px-4 py-2 text-sm font-semibold">Simpan Mapping</button></form></Card>
  </section>}

  <section className="grid gap-5 xl:grid-cols-2"><Card title="Ticket Terbaru"><div className="space-y-2 max-h-[480px] overflow-auto">{tickets.map(t=><div key={t.id} className="rounded-lg border border-slate-200 p-3"><div className="flex justify-between gap-3"><div><b className="text-[#0f6cbd]">{t.ticket_number}</b> · {t.subject}<div className="text-xs text-slate-500">{t.customer?.customer_number} · {t.customer?.name} · {t.technician?.name||'unassigned'}</div></div><Badge v={t.status}/></div>{canManage&&<div className="mt-2 flex flex-wrap gap-2">{['in_progress','waiting_customer','resolved','closed'].map(s=><button key={s} onClick={()=>router.put(`/field-operations/tickets/${t.id}/status`,{status:s},{preserveScroll:true})} className="rounded bg-slate-100 px-2 py-1 text-[10px]">{s}</button>)}</div>}</div>)}{!tickets.length&&<Empty/>}</div></Card><Card title="Work Order"><div className="space-y-2 max-h-[480px] overflow-auto">{workOrders.map(w=><div key={w.id} className="rounded-lg border border-slate-200 p-3"><div className="flex justify-between"><div><b>{w.work_order_number}</b> · {w.type}<div className="text-xs text-slate-500">{w.customer?.customer_number} · {w.technician?.name||'unassigned'}</div></div><Badge v={w.status}/></div>{canManage&&<div className="mt-2 flex gap-2">{['assigned','on_the_way','on_site','completed'].map(s=><button key={s} onClick={()=>router.put(`/field-operations/work-orders/${w.id}/status`,{status:s},{preserveScroll:true})} className="rounded bg-slate-100 px-2 py-1 text-[10px]">{s}</button>)}</div>}</div>)}{!workOrders.length&&<Empty/>}</div></Card></section>

  <section className="grid gap-5 xl:grid-cols-2">
   <Card title="Installation Workflow"><div className="space-y-2 max-h-[430px] overflow-auto">{installations.map(i=><div key={i.id} className="rounded-lg border border-slate-200 p-3"><div className="flex justify-between gap-3"><div><b>{i.installation_number}</b><div className="text-xs text-slate-500">{i.service?.customer?.customer_number} · {i.service?.customer?.name} · {i.service?.service_number}</div><div className="text-xs text-slate-500">Teknisi: {i.technician?.name||'unassigned'}</div></div><Badge v={i.status}/></div>{canManage&&<div className="mt-2 flex flex-wrap gap-2">{['scheduled','on_the_way','on_site','activated','completed'].map(s=><button key={s} onClick={()=>router.put(`/field-operations/installations/${i.id}/status`,{status:s},{preserveScroll:true})} className="rounded bg-slate-100 px-2 py-1 text-[10px]">{s}</button>)}</div>}</div>)}{!installations.length&&<Empty/>}</div></Card>
   <Card title="Technician Roster"><div className="space-y-2 max-h-[430px] overflow-auto">{technicians.map(t=><div key={t.id} className="rounded-lg border border-slate-200 p-3"><div className="flex justify-between"><div><b>{t.code}</b> · {t.name}<div className="text-xs text-slate-500">{t.phone||'-'} · {(t.skills||[]).join(', ')||'no skills'}</div></div><Badge v={t.status}/></div></div>)}{!technicians.length&&<Empty/>}</div></Card>
  </section>

  <section className="grid gap-5 xl:grid-cols-2"><Card title="Inventory"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-xs text-slate-500"><tr><th>Asset</th><th>Type</th><th>Status</th><th>Assigned</th></tr></thead><tbody>{inventory.map(i=><tr key={i.id} className="border-t border-slate-200"><td className="py-2">{i.asset_code}<div className="text-xs text-slate-500">{i.brand} {i.model}</div></td><td>{i.category}</td><td><Badge v={i.status}/></td><td>{i.service?.service_number||i.technician?.name||'-'}</td></tr>)}</tbody></table></div></Card><Card title="ODP/ODC & Network Nodes"><div className="space-y-2 max-h-[430px] overflow-auto">{nodes.map(n=><div key={n.id} className="flex items-center justify-between rounded-lg border border-slate-200 p-3"><div><b>{n.code}</b> · {n.name}<div className="text-xs text-slate-500">{n.node_type.toUpperCase()} · ports {n.used_ports}/{n.capacity_ports||'-'}</div></div><Badge v={n.status}/></div>)}{!nodes.length&&<Empty/>}</div></Card></section>

  <Card title="GIS Lite — Customer & Network Coordinates"><Gis points={mapPoints}/></Card>
 </div></Layout>
}
function Gis({points}:{points:any[]}){if(!points.length)return <Empty/>;const xs=points.map(p=>Number(p.longitude)),ys=points.map(p=>Number(p.latitude));const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const pos=(p:any)=>({x:30+(Number(p.longitude)-minX)/(maxX-minX||1)*740,y:370-(Number(p.latitude)-minY)/(maxY-minY||1)*330});return <div><svg viewBox="0 0 800 400" className="w-full rounded-xl border border-slate-200 bg-white"><path d="M30 40H770V370H30Z" fill="none" stroke="currentColor" className="text-slate-800"/>{points.map((p,i)=>{const q=pos(p);return <g key={`${p.kind}-${p.id}-${i}`}><circle cx={q.x} cy={q.y} r={p.kind==='node'?7:5} className={p.kind==='node'?'fill-violet-500':'fill-blue-500'}/><text x={q.x+8} y={q.y-6} fontSize="10" className="fill-slate-400">{p.code}</text></g>})}</svg><div className="mt-2 text-xs text-slate-500">Plot koordinat operasional tanpa tile eksternal. Titik biru = pelanggan, ungu = node jaringan. Data latitude/longitude tetap dapat diekspor/dikembangkan ke Leaflet/OSM.</div></div>}
function Card({title,children}:{title:string,children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="mb-4 text-base font-black text-slate-800">{title}</h3>{children}</section>}
function Metric({label,value}:{label:string,value:any}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}</div><div className="mt-1 text-xl font-black text-slate-900">{String(value)}</div></div>}
function Badge({v}:{v:string}){const ok=['active','completed','resolved','available'].includes(v),warn=['open','planned','assigned','on_site','in_progress'].includes(v);return <span className={`rounded px-2 py-1 text-[10px] uppercase ${ok?'bg-emerald-50 text-emerald-700':warn?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-700'}`}>{v}</span>}
function Empty(){return <div className="py-6 text-center text-sm text-slate-500">Belum ada data.</div>}
