import React,{useMemo} from 'react';
import {useForm,usePage} from '@inertiajs/react';
import InventoryLayout from '../../components/InventoryLayout';
import {Boxes,PackageCheck,PackageOpen,RefreshCcw,ScanLine,TriangleAlert,Warehouse} from 'lucide-react';
const money=(n:any)=>'Rp'+new Intl.NumberFormat('id-ID').format(Number(n||0));
const qty=(n:any)=>new Intl.NumberFormat('id-ID',{maximumFractionDigits:3}).format(Number(n||0));
const input='mt-1.5 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100';
const btn='rounded-xl bg-[#0f6cbd] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50';
const panel='rounded-2xl border border-slate-200 bg-white p-5 shadow-sm';
function Field({label,help,children}:any){return <label className="block text-sm font-semibold text-slate-700">{label}{children}{help&&<span className="mt-1 block text-xs font-normal text-slate-400">{help}</span>}</label>}
function PoReceive({purchase,slug}:any){const item=purchase.items?.[0];const f=useForm({purchase_item_id:item?.id||'',quantity:item?String(Math.max(0,Number(item.quantity)-Number(item.received_quantity))):'0',serials:'',notes:''});if(!item||purchase.status==='received'||purchase.status==='canceled')return null;return <form className="mt-3 grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();f.post(`/inventory/${slug}/purchases/${purchase.id}/receive`,{preserveScroll:true})}}><Field label="Jumlah diterima"><input className={input} type="number" min="0" step="0.001" value={f.data.quantity} onChange={e=>f.setData('quantity',e.target.value)}/></Field>{item.sku?.serialized&&<div className="md:col-span-2"><Field label="Serial Number / MAC / Barcode" help="Satu unit per baris, format: SN,MAC,BARCODE"><textarea className={input} rows={3} value={f.data.serials} onChange={e=>f.setData('serials',e.target.value)}/></Field></div>}<div className="md:col-span-2"><Field label="Catatan penerimaan (opsional)"><input className={input} value={f.data.notes} onChange={e=>f.setData('notes',e.target.value)}/></Field></div><button className={btn} disabled={f.processing}>Terima Barang PO</button></form>}
export default function Dashboard({stats,locations,skus,balances,assets,transactions,suppliers,purchases,services,account}:any){
 const page:any=usePage().props;const slug=page.tenant.slug;const manager=account.role==='warehouse_manager';const writable=['warehouse_manager','warehouse_staff','technician'].includes(account.role);const warehouseWrite=['warehouse_manager','warehouse_staff'].includes(account.role);
 const receive=useForm({to_location_id:account.location_id||locations[0]?.id||'',inventory_sku_id:skus[0]?.id||'',quantity:'1',unit_cost:'0',supplier_id:'',purchase_order_id:'',serials:'',notes:''});
 const transfer=useForm({from_location_id:account.location_id||locations[0]?.id||'',to_location_id:locations[1]?.id||locations[0]?.id||'',inventory_sku_id:skus[0]?.id||'',quantity:'1',asset_ids:[] as number[],notes:''});
 const install=useForm({asset_id:'',customer_service_id:services[0]?.id||'',notes:''});
 const retrieve=useForm({asset_id:'',to_location_id:account.location_id||locations[0]?.id||'',condition:'good',notes:''});
 const opname=useForm({inventory_location_id:account.location_id||locations[0]?.id||'',inventory_sku_id:skus[0]?.id||'',counted_quantity:'0',notes:''});
 const skuForm=useForm({sku:'',name:'',category:'ont',brand:'',model:'',uom:'pcs',minimum_stock:'0',serialized:false,track_mac:false});
 const supplier=useForm({code:'',name:'',contact_name:'',phone:'',email:'',address:'',tax_number:'',notes:''});
 const po=useForm({supplier_id:suppliers[0]?.id||'',destination_location_id:locations[0]?.id||'',inventory_sku_id:skus[0]?.id||'',quantity:'1',unit_cost:'0',expected_at:'',notes:''});
 const password=useForm({current_password:'',password:'',password_confirmation:''});
 const selectedTransferSku=useMemo(()=>skus.find((x:any)=>String(x.id)===String(transfer.data.inventory_sku_id)),[skus,transfer.data.inventory_sku_id]);
 const transferableAssets=assets.filter((x:any)=>String(x.inventory_sku_id)===String(transfer.data.inventory_sku_id)&&String(x.current_location_id)===String(transfer.data.from_location_id));
 const installedAssets=assets.filter((x:any)=>x.status==='assigned_customer');
 const statsCards=[['SKU Aktif',stats.sku,Boxes,'bg-blue-50 text-blue-700'],['Total Asset',stats.assets,ScanLine,'bg-cyan-50 text-cyan-700'],['Asset Tersedia',stats.available_assets,PackageCheck,'bg-emerald-50 text-emerald-700'],['Terpasang Customer',stats.installed_assets,PackageOpen,'bg-violet-50 text-violet-700'],['Low Stock',stats.low_stock,TriangleAlert,'bg-amber-50 text-amber-700'],['Lokasi Stok',stats.locations,Warehouse,'bg-slate-100 text-slate-700']];
 return <InventoryLayout tenantSlug={slug}>
  <div className="mb-6 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h1 className="text-2xl font-black">Inventory & Warehouse</h1><p className="mt-1 text-sm text-slate-500">Kelola stok gudang, stok teknisi, SN/MAC, purchase order, instalasi asset dan stock opname.</p></div><div className="rounded-xl bg-white px-4 py-2 text-xs text-slate-500 shadow-sm ring-1 ring-slate-200">Lokasi akun: <b className="text-slate-700">{page.inventory?.location?.name||'Semua lokasi'}</b></div></div>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{statsCards.map(([label,value,Icon,tone]:any)=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><div className="text-[11px] font-bold uppercase tracking-wide text-slate-400">{label}</div><div className="mt-1 text-2xl font-black">{value}</div></div><div className={`rounded-xl p-2 ${tone}`}><Icon size={18}/></div></div></div>)}</div>
  <div className="mt-6 grid gap-5 xl:grid-cols-2"><section className={panel}><h2 className="font-bold">Saldo Stok per Lokasi</h2><p className="mt-1 text-xs text-slate-500">On-hand stock dan indikator minimum stock.</p><div className="mt-4 max-h-80 overflow-auto"><table className="w-full min-w-[620px] text-sm"><thead><tr className="border-y border-slate-100 bg-slate-50 text-left text-xs text-slate-400"><th className="px-3 py-3">Lokasi</th><th>SKU / Barang</th><th className="pr-3 text-right">On Hand</th></tr></thead><tbody>{balances.map((b:any)=><tr key={b.id} className="border-b border-slate-100"><td className="px-3 py-3">{b.location?.code} · {b.location?.name}</td><td>{b.sku?.sku} · {b.sku?.name}</td><td className={`pr-3 text-right font-semibold ${(Number(b.quantity_on_hand)<=Number(b.sku?.minimum_stock||0)&&Number(b.sku?.minimum_stock)>0)?'text-amber-600':''}`}>{qty(b.quantity_on_hand)} {b.sku?.uom}</td></tr>)}</tbody></table></div></section>
   <section className={panel}><h2 className="font-bold">Movement Terbaru</h2><p className="mt-1 text-xs text-slate-500">Jejak barang masuk, keluar, transfer, install dan retrieve.</p><div className="mt-3 max-h-80 overflow-auto divide-y divide-slate-100">{transactions.map((t:any)=><div key={t.id} className="flex justify-between gap-3 py-3 text-sm"><div><div className="font-semibold">{t.transaction_number} · <span className="capitalize">{String(t.transaction_type).replaceAll('_',' ')}</span></div><div className="text-xs text-slate-500">{t.from_location?.name||'—'} → {t.to_location?.name||'—'} · {new Date(t.occurred_at).toLocaleString('id-ID')}</div></div><div className="max-w-52 text-right text-xs text-slate-500">{t.lines?.map((l:any)=>`${l.sku?.sku} ${qty(l.quantity)}`).join(', ')}</div></div>)}{!transactions.length&&<div className="py-8 text-center text-sm text-slate-400">Belum ada movement.</div>}</div></section></div>

  {warehouseWrite&&<div className="mt-6 grid gap-5 xl:grid-cols-2"><section className={panel}><h2 className="font-bold">Barang Masuk / Receive</h2><p className="mt-1 text-xs text-slate-500">Catat penerimaan barang ke lokasi stok.</p><form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();receive.post(`/inventory/${slug}/receive`,{preserveScroll:true})}}><Field label="Lokasi penerimaan"><select className={input} value={receive.data.to_location_id} onChange={e=>receive.setData('to_location_id',e.target.value)}>{locations.map((x:any)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></Field><Field label="SKU / Barang"><select className={input} value={receive.data.inventory_sku_id} onChange={e=>receive.setData('inventory_sku_id',e.target.value)}>{skus.map((x:any)=><option key={x.id} value={x.id}>{x.sku} · {x.name}{x.serialized?' [SERIAL]':''}</option>)}</select></Field><Field label="Jumlah diterima"><input className={input} type="number" min="0" step="0.001" value={receive.data.quantity} onChange={e=>receive.setData('quantity',e.target.value)}/></Field><Field label="Harga beli per unit"><input className={input} type="number" min="0" step="1" value={receive.data.unit_cost} onChange={e=>receive.setData('unit_cost',e.target.value)}/></Field><Field label="Supplier (opsional)"><select className={input} value={receive.data.supplier_id} onChange={e=>receive.setData('supplier_id',e.target.value)}><option value="">Tanpa supplier</option>{suppliers.map((x:any)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></Field><div className="md:col-span-2"><Field label="Serial Number / MAC / Barcode" help="Khusus serialized item: satu unit per baris dengan format SN,MAC,BARCODE."><textarea className={input} rows={3} value={receive.data.serials} onChange={e=>receive.setData('serials',e.target.value)}/></Field></div><div className="md:col-span-2"><Field label="Catatan (opsional)"><input className={input} value={receive.data.notes} onChange={e=>receive.setData('notes',e.target.value)}/></Field></div><button className={btn} disabled={receive.processing}>Simpan Barang Masuk</button></form></section>
   <section className={panel}><h2 className="font-bold">Transfer / Issue Teknisi</h2><p className="mt-1 text-xs text-slate-500">Pindahkan barang antar gudang atau ke stok teknisi.</p><form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();transfer.post(`/inventory/${slug}/transfer`,{preserveScroll:true})}}><Field label="Dari lokasi"><select className={input} value={transfer.data.from_location_id} onChange={e=>transfer.setData('from_location_id',e.target.value)}>{locations.map((x:any)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></Field><Field label="Ke lokasi"><select className={input} value={transfer.data.to_location_id} onChange={e=>transfer.setData('to_location_id',e.target.value)}>{locations.map((x:any)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></Field><Field label="SKU / Barang"><select className={input} value={transfer.data.inventory_sku_id} onChange={e=>{transfer.setData('inventory_sku_id',e.target.value);transfer.setData('asset_ids',[])}}>{skus.map((x:any)=><option key={x.id} value={x.id}>{x.sku} · {x.name}</option>)}</select></Field><Field label="Jumlah"><input className={input} type="number" min="0" step="0.001" value={transfer.data.quantity} onChange={e=>transfer.setData('quantity',e.target.value)}/></Field>{selectedTransferSku?.serialized&&<div className="md:col-span-2"><Field label="Pilih asset serialized" help="Gunakan Ctrl/Shift untuk memilih beberapa unit."><select multiple size={Math.min(6,Math.max(3,transferableAssets.length))} className={input} value={transfer.data.asset_ids.map(String)} onChange={e=>transfer.setData('asset_ids',Array.from(e.currentTarget.selectedOptions).map(o=>Number(o.value)))}>{transferableAssets.map((a:any)=><option key={a.id} value={a.id}>{a.asset_code} · {a.serial_number} · {a.mac_address||'-'}</option>)}</select></Field></div>}<div className="md:col-span-2"><Field label="Catatan transfer"><input className={input} value={transfer.data.notes} onChange={e=>transfer.setData('notes',e.target.value)}/></Field></div><button className={btn} disabled={transfer.processing}>Post Transfer</button></form></section></div>}

  {writable&&<div className="mt-6 grid gap-5 xl:grid-cols-2"><section className={panel}><h2 className="font-bold">Install Asset ke Customer</h2><form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();install.post(`/inventory/${slug}/install`,{preserveScroll:true})}}><Field label="Asset yang dipasang"><select className={input} value={install.data.asset_id} onChange={e=>install.setData('asset_id',e.target.value)}><option value="">Pilih asset</option>{assets.filter((a:any)=>a.current_location_id&&['available','assigned_technician'].includes(a.status)).map((a:any)=><option key={a.id} value={a.id}>{a.asset_code} · {a.sku?.name||a.model} · {a.serial_number||'-'}</option>)}</select></Field><Field label="Layanan pelanggan"><select className={input} value={install.data.customer_service_id} onChange={e=>install.setData('customer_service_id',e.target.value)}>{services.map((s:any)=><option key={s.id} value={s.id}>{s.service_number} · {s.customer?.customer_number} {s.customer?.name}</option>)}</select></Field><div className="md:col-span-2"><Field label="Catatan instalasi"><input className={input} value={install.data.notes} onChange={e=>install.setData('notes',e.target.value)}/></Field></div><button className={btn} disabled={install.processing}>Pasang Asset</button></form></section>
   <section className={panel}><h2 className="font-bold">Retrieve Asset Customer</h2><form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();retrieve.post(`/inventory/${slug}/retrieve`,{preserveScroll:true})}}><Field label="Asset terpasang"><select className={input} value={retrieve.data.asset_id} onChange={e=>retrieve.setData('asset_id',e.target.value)}><option value="">Pilih asset</option>{installedAssets.map((a:any)=><option key={a.id} value={a.id}>{a.asset_code} · {a.serial_number||'-'}</option>)}</select></Field><Field label="Kembali ke lokasi"><select className={input} value={retrieve.data.to_location_id} onChange={e=>retrieve.setData('to_location_id',e.target.value)}>{locations.map((x:any)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></Field><Field label="Kondisi saat kembali"><select className={input} value={retrieve.data.condition} onChange={e=>retrieve.setData('condition',e.target.value)}><option value="good">Baik / Good</option><option value="repair">Perlu Repair</option><option value="damaged">Rusak</option></select></Field><Field label="Catatan"><input className={input} value={retrieve.data.notes} onChange={e=>retrieve.setData('notes',e.target.value)}/></Field><button className={btn} disabled={retrieve.processing}>Retrieve Asset</button></form></section></div>}

  {warehouseWrite&&<section className={`${panel} mt-6`}><h2 className="font-bold">Stock Opname</h2><p className="mt-1 text-xs text-slate-500">Bandingkan stok fisik dengan saldo sistem dan catat variance pada ledger.</p><form className="mt-4 grid gap-3 md:grid-cols-4" onSubmit={e=>{e.preventDefault();opname.post(`/inventory/${slug}/stock-opname`,{preserveScroll:true})}}><Field label="Lokasi"><select className={input} value={opname.data.inventory_location_id} onChange={e=>opname.setData('inventory_location_id',e.target.value)}>{locations.map((x:any)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></Field><Field label="SKU / Barang"><select className={input} value={opname.data.inventory_sku_id} onChange={e=>opname.setData('inventory_sku_id',e.target.value)}>{skus.map((x:any)=><option key={x.id} value={x.id}>{x.sku} · {x.name}</option>)}</select></Field><Field label="Jumlah fisik"><input className={input} type="number" min="0" step="0.001" value={opname.data.counted_quantity} onChange={e=>opname.setData('counted_quantity',e.target.value)}/></Field><div className="flex items-end"><button className={`${btn} w-full`} disabled={opname.processing}>Post Opname</button></div></form></section>}

  {manager&&<div className="mt-6 grid gap-5 xl:grid-cols-3"><section className={panel}><h2 className="font-bold">Master SKU</h2><form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();skuForm.post(`/inventory/${slug}/skus`,{preserveScroll:true,onSuccess:()=>skuForm.reset()})}}><Field label="Kode SKU"><input className={input} value={skuForm.data.sku} onChange={e=>skuForm.setData('sku',e.target.value)} placeholder="ONT-HW-01"/></Field><Field label="Nama barang"><input className={input} value={skuForm.data.name} onChange={e=>skuForm.setData('name',e.target.value)} placeholder="ONT Huawei..."/></Field><div className="grid grid-cols-2 gap-2"><Field label="Kategori"><input className={input} value={skuForm.data.category} onChange={e=>skuForm.setData('category',e.target.value)}/></Field><Field label="Satuan"><input className={input} value={skuForm.data.uom} onChange={e=>skuForm.setData('uom',e.target.value)} placeholder="pcs"/></Field></div><div className="grid grid-cols-2 gap-2"><Field label="Brand"><input className={input} value={skuForm.data.brand} onChange={e=>skuForm.setData('brand',e.target.value)}/></Field><Field label="Model"><input className={input} value={skuForm.data.model} onChange={e=>skuForm.setData('model',e.target.value)}/></Field></div><Field label="Minimum stock"><input className={input} type="number" min="0" value={skuForm.data.minimum_stock} onChange={e=>skuForm.setData('minimum_stock',e.target.value)}/></Field><div className="flex flex-wrap gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={skuForm.data.serialized} onChange={e=>skuForm.setData('serialized',e.target.checked)}/> Tracking serial number</label><label className="flex items-center gap-2"><input type="checkbox" checked={skuForm.data.track_mac} onChange={e=>skuForm.setData('track_mac',e.target.checked)}/> Tracking MAC</label></div><button className={btn} disabled={skuForm.processing}>Tambah SKU</button></form></section>
   <section className={panel}><h2 className="font-bold">Supplier</h2><form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();supplier.post(`/inventory/${slug}/suppliers`,{preserveScroll:true,onSuccess:()=>supplier.reset()})}}><Field label="Kode supplier"><input className={input} value={supplier.data.code} onChange={e=>supplier.setData('code',e.target.value)} placeholder="SUP-001"/></Field><Field label="Nama supplier"><input className={input} value={supplier.data.name} onChange={e=>supplier.setData('name',e.target.value)}/></Field><Field label="Nama kontak"><input className={input} value={supplier.data.contact_name} onChange={e=>supplier.setData('contact_name',e.target.value)}/></Field><div className="grid grid-cols-2 gap-2"><Field label="Telepon"><input className={input} value={supplier.data.phone} onChange={e=>supplier.setData('phone',e.target.value)}/></Field><Field label="Email"><input className={input} type="email" value={supplier.data.email} onChange={e=>supplier.setData('email',e.target.value)}/></Field></div><button className={btn} disabled={supplier.processing}>Tambah Supplier</button></form></section>
   <section className={panel}><h2 className="font-bold">Purchase Order</h2><form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();po.post(`/inventory/${slug}/purchases`,{preserveScroll:true})}}><Field label="Supplier"><select className={input} value={po.data.supplier_id} onChange={e=>po.setData('supplier_id',e.target.value)}><option value="">Pilih supplier</option>{suppliers.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Lokasi tujuan"><select className={input} value={po.data.destination_location_id} onChange={e=>po.setData('destination_location_id',e.target.value)}>{locations.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Barang"><select className={input} value={po.data.inventory_sku_id} onChange={e=>po.setData('inventory_sku_id',e.target.value)}>{skus.map((x:any)=><option key={x.id} value={x.id}>{x.sku} · {x.name}</option>)}</select></Field><div className="grid grid-cols-2 gap-2"><Field label="Jumlah"><input className={input} type="number" min="0" step="0.001" value={po.data.quantity} onChange={e=>po.setData('quantity',e.target.value)}/></Field><Field label="Harga/unit"><input className={input} type="number" min="0" step="1" value={po.data.unit_cost} onChange={e=>po.setData('unit_cost',e.target.value)}/></Field></div><Field label="Perkiraan tiba"><input className={input} type="date" value={po.data.expected_at} onChange={e=>po.setData('expected_at',e.target.value)}/></Field><button className={btn} disabled={po.processing}>Buat Purchase Order</button></form></section></div>}

  {manager&&<section className={`${panel} mt-6`}><h2 className="font-bold">Purchase Orders</h2><div className="mt-4 grid gap-3 lg:grid-cols-2">{purchases.map((p:any)=><div key={p.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><div><div className="font-semibold">{p.po_number} · {p.supplier?.name}</div><div className="text-xs text-slate-500">Tujuan: {p.destination?.name} · {p.status}</div></div><div className="font-bold">{money(p.total_amount)}</div></div><div className="mt-2 text-xs text-slate-500">{p.items?.map((i:any)=>`${i.sku?.sku} ${qty(i.received_quantity)}/${qty(i.quantity)}`).join(', ')}</div><PoReceive purchase={p} slug={slug}/></div>)}{!purchases.length&&<div className="py-8 text-center text-sm text-slate-400">Belum ada purchase order.</div>}</div></section>}

  <section className={`${panel} mt-6`}><h2 className="font-bold">Asset Registry — Serial Number / MAC</h2><div className="mt-4 max-h-96 overflow-auto"><table className="w-full min-w-[780px] text-sm"><thead><tr className="border-y border-slate-100 bg-slate-50 text-left text-xs text-slate-400"><th className="px-3 py-3">Asset</th><th>SKU</th><th>Serial / MAC</th><th>Lokasi</th><th>Status</th></tr></thead><tbody>{assets.map((a:any)=><tr key={a.id} className="border-b border-slate-100"><td className="px-3 py-3 font-mono text-xs text-[#0f6cbd]">{a.asset_code}</td><td>{a.sku?.sku} · {a.sku?.name}</td><td>{a.serial_number||'-'}<div className="text-xs text-slate-500">{a.mac_address||'-'}</div></td><td>{a.location?.name||(a.status==='assigned_customer'?'Customer':'—')}</td><td className="capitalize">{String(a.status).replaceAll('_',' ')} · {a.condition}</td></tr>)}</tbody></table></div></section>

  <section className={`${panel} mt-6`}><div className="flex items-center gap-2"><RefreshCcw size={18} className="text-[#0f6cbd]"/><h2 className="font-bold">Keamanan Akun Inventory</h2></div>{page.inventory?.account?.must_change_password&&<div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-700">Password sementara wajib diganti sebelum melakukan transaksi.</div>}<form className="mt-4 grid gap-3 md:grid-cols-4" onSubmit={e=>{e.preventDefault();password.put(`/inventory/${slug}/password`,{preserveScroll:true,onSuccess:()=>password.reset()})}}><Field label="Password saat ini"><input className={input} type="password" value={password.data.current_password} onChange={e=>password.setData('current_password',e.target.value)}/></Field><Field label="Password baru"><input className={input} type="password" value={password.data.password} onChange={e=>password.setData('password',e.target.value)}/></Field><Field label="Konfirmasi password"><input className={input} type="password" value={password.data.password_confirmation} onChange={e=>password.setData('password_confirmation',e.target.value)}/></Field><div className="flex items-end"><button className={`${btn} w-full`} disabled={password.processing}>Ganti Password</button></div></form></section>
 </InventoryLayout>;
}
